### ISSUE TITLE
Status updates via slack or mail

### ISSUE THREAD

**Issue by davevs** [OWASP/django-DefectDojo#100]
Many agile teams like push notifications in case of status changes, instead of checking a status overview. For example, teams I work with use Slack to have Jenkins notify them of things that are going on. I think it would really help if each team in ddojo can list a slack channel where status changes can be pushed to.

e.g.:
New nikto import: 0C - 1H - 2M - 3L
Issue 156 has been accepted
Issue 134 pushed to Jira

**Comment by aaronweaver** [comment]
@devevs Would the new metadata option work? In the product view >> dropdown on right >> select 'Add metadata' >> Name: Slack then the channels or preferred communication. See the screenshot. Product information shows up on 'Additional Information' in the product view.

Or were you looking for Dojo to push out a status to Slack?

![aaron_test_product](https://cloud.githubusercontent.com/assets/220838/17972741/c064bcbe-6aad-11e6-9c54-8d9f2f39f855.png)

**Comment by davevs** [comment]
@aaronweaver yeah I meant an active push to a slack channel. Some sort of messaging system.

**Comment by aaronweaver** [comment]
@davevs What would be the criteria on when you'd like to push to a slack channel? For example:

- Vulnerability scanner test imported, auto post those results to slack channel. (Might be noisy especially with multi-tests. Maybe on engagement close?
- Option to send summary as a cron with the option to push finding summaries to a specific channel. 
- Have the option to only post summary data when something changes. (new finding, finding closed etc.)

**Comment by davevs** [comment]
I wouldn't post to many details as this would clutter the channel feed. If you look e.g. at Jenkins it typically sends messages like 'Build run XXX failed after y sec.' 
We might also give a small summary like 0C/1H/2M/3L/4I added
It might also be interesting to send a message when a status has changed, but that might be to 'chatty'

**Comment by devGregA** [comment]
## Status Updates via Slack and/or Mail

### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to configure slack / email notifications for issues.

Implementation Requirements:

- [ ] Create a configuration page that has a checkbox matrix to assign when notifications will be sent out.
- [ ] Integrate with slack APIs to push issues to a **channel**
- [ ] Use the email intregration present with scan profiles to send notifications via this new system.
- [ ] Add documentation to the /docs folder.

Resources:
Slack Documentation:  https://api.slack.com/custom-integrations

**Comment by devGregA** [comment]
Rewrote in #228 for clarity
