### ISSUE TITLE
SAML 2 Integration

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#102]
Have the ability to integrate with service providers using SAML. One possible library to use is: https://pypi.python.org/pypi/djangosaml2/

**Comment by grendel513** [comment]
Django uses Authentication Middleware see https://docs.djangoproject.com/en/1.8/ref/middleware/#module-django.contrib.auth.middleware

There are already SAML 2 libraries out there that you can include in your individual installation to implement SAML 2 auth. https://pypi.python.org/pypi/djangosaml2/

**Comment by aaronweaver** [comment]
@grendel513 Thanks, I'll give that a try. Would it be worth me documenting that and then doing a PR? I'm sure some organizations would like integration with LDAP/SAML.

**Comment by devGregA** [comment]
Hi @aaronweaver  I added links in the reademe to the SAML and LDAP plugins.
