### ISSUE TITLE
Remove all docs that aren't 'Read The Docs'?

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#105]
The wiki and the doc folder seem to have outdated information. To make navigation less confusing shoudl we remove them?

**Comment by devGregA** [comment]
@grendel513

**Comment by devGregA** [comment]
bump @grendel513 @aaronweaver @cneill @mtesauro

**Comment by mtesauro** [comment]
I will read through these tonight and reply tomorrow with my 2 cents.  Anything I say now will be uninformed.

**Comment by mtesauro** [comment]
I'd say leave them there for the time being. Perhaps a couple of the install ones could be removed as they are not accurate and should be re-written after the setup.bash script get some love.  I have that work planned for the week of October 17th.
