### ISSUE TITLE
PDF report generation hangs

### ISSUE THREAD

**Issue by tmsteen** [OWASP/django-DefectDojo#107]
When generating a PDF report, it just shows that it is running but never completes.  

Results of `celery -A dojo worker -l info --concurrency 3`

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 235, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dojo

**Comment by grendel513** [comment]
@tmsteen - are you using virtual environments?  This looks like your python environment when executing celery is different than the one you have DefectDojo installed in.

**Comment by tmsteen** [comment]
Not intentionally.  The person who installed this is no longer here and did not leave any documentation.  Is it worth trying to fix or just reinstall?

**Comment by grendel513** [comment]
@tmsteen it depends how much data you have already generated/imported.  You can try and figure out where they installed it and if they used a virtualenv - I would start with the supervisor configuration file, as it will point to where the python executable is.  You can also look in /.virtualenvs to see if any virtual environments have been set up that may point to the appropriate site-packages, but this may not work since virtual environments can be set up anywhere.

You can also run a `ps -ef | grep python` to see the currently running python processes, one may point you to the virtual env version.

**Comment by grendel513** [comment]
@tmsteen - you can also install http://virtualenvwrapper.readthedocs.io/en/latest/index.html to find out what virtual environments are installed on the box.  Your milage may vary since you may not know where the virtual env was set up to begin with.

**Comment by devGregA** [comment]
@tmsteen  Does it immediately fail? It sounds to me like you're running it in the wrong directory.

**Comment by devGregA** [comment]
you should be inside the django-DefectDojo directory but not in the dojo directory

**Comment by tmsteen** [comment]
That was the issue, but in my process of trying to remediate the issue I broke it further. Now getting a template error when trying to access DD.  This is a separate issue that started after I "attempted" to fix the current installation.

**Comment by devGregA** [comment]
@grendel513 @tmsteen this is one I'm not familiar with. @grendel513 do you think it is worth trying an upgrade or trying to debug the current version? I'm in favor of getting him on the latest version. @tmsteen I could assist via google hangout.

**Comment by tmsteen** [comment]
Update:  Got it up and running again.  I think that was a separate issue the I encountered after I did a `git pull`.  I can create an issue for that if needed with the details. After fixing that issue, I am now running another report just to make sure updating did not change anything but it still looks like reports are hanging. 

Running the celery command from the DefectDojo directory still produces errors. 

Happy to do a hangout if you have time for it.

**Comment by devGregA** [comment]
Nice! Let me know if you continue to have issues. Happy to hop on hangout and assist.

**Comment by tmsteen** [comment]
ya if we can do a hangout that would help.  just so I know how best to proceed without being a huge PITA.  Nothing in my calendar until 2:30.

**Comment by devGregA** [comment]
shoot me an email @ greg.anderson@owasp.org and I'll shoot you an email

**Comment by devGregA** [comment]
@tmsteen bumped to 1:30 to give you additional time for lunch. Let me know if a different time is better.

**Comment by devGregA** [comment]
@grendel513 @aaronweaver  got em running but discovered lots of issues. I believe dependencies are missing for tagging, imagekit, etc. reports/views.py line 41 def report_url_resolver(request): doesn't work for instances that aren't dockerized. I had to do a custom fix.

**Comment by aaronweaver** [comment]
@devGregA I'll look at possibly converging the setup.bash and docker bash setup. That way the travis build can test both.

**Comment by devGregA** [comment]
thanks @aaronweaver  greatly appreciated!

**Comment by tmsteen** [comment]
After the update with @devGregA yesterday, it appears that the issue is resolved.  Recommend close this issue.

**Comment by devGregA** [comment]
@aaronweaver can we just copy the docker bash script? I don't recall them differing by that much?

**Comment by aaronweaver** [comment]
There are some minor differences. I'll take a look.
