### ISSUE TITLE
Software Bill of Materials

### ISSUE THREAD

**Issue by mattvaldes** [OWASP/django-DefectDojo#109]
For a Product and/or Engagement, the ability to catalog a software bill of materials would be useful.    _Would this be more appropriate as a plugin?_

Simple example (assuming manual input):

| Name | Version | Source |
| --- | --- | --- |
| Python | 2.7 | Python.org |
| Python Requests | 2.11.1 | https://github.com/kennethreitz/requests |
| CentOS | 6.8 | https://cent-repo.internal.com |
| nginx | 1.11.2 | CentOS epel |

This could potentially be imported using requirements.txt or similar structured lists. 
These fields should then be searchable across products and/or engagements for version tracking, patch management, etc. 

Thanks!

**Comment by aaronweaver** [comment]
@mattvaldes I think it would be appropriate in core Dojo. The tagging/metadata effort on the product level was the first attempt at getting to that. 

I'm wondering if metadata was extended to the API and then integrated with a script/API/service to pull the necessary metadata and dump it into Dojo. I've been thinking about using http://cloc.sourceforge.net/ to at least get part way there. Not sure what other apps might be able to parse out that information. Ideally I think the gathering of the info would be done outside of dojo and then pushed in via the API.

Language | files | blank | comment | code
----------|------|-------|----------|------
C++ | 10 |            312 |           277    |       2000
XML               |              26     |       231        |      0       |    1972

**Comment by mattvaldes** [comment]
@aaronweaver Thanks for the feedback. I haven't used the tags or metadata fields, but did consider presenting this as a more generic key-value store to support any number of different data sets. I'll review these features.
Implementing this at a product level should work, but the ability to track changes over time would be useful/important (as opposed to overwriting the entries on each change), which is why I suggested engagement level as well.
I agree that the data should be gathered outside of Dojo and input through the API and/or a form if possible.

**Comment by devGregA** [comment]
@grendel513 @aaronweaver @mtesauro  do y'all think this is covered w/ the new meta data feature?

**Comment by devGregA** [comment]
Closing. Please see my previous comment. Feel free to reopen if you disagree
