### ISSUE TITLE
setup.bash doesn't work

### ISSUE THREAD

**Issue by opsdisk** [OWASP/django-DefectDojo#110]
Tried installing on vanilla 14.04.3 x64.

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rack/Desktop/django-DefectDojo/dojo/__init__.py", line 5, in <module>
    from .celery import app as celery_app  # noqa
  File "/home/rack/Desktop/django-DefectDojo/dojo/celery.py", line 3, in <module>
    from celery import Celery
ImportError: No module named celery
==============================================================================

SUCCESS! Now edit your settings.py file in the 'dojo' directory to complete the installation.

We suggest you consider changing the following defaults:

    DEBUG = True  # you should set this to False when you are ready for production.
    Uncomment the following lines if you enabled SSL/TLS on your server:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')
        SECURE_SSL_REDIRECT = True
        SECURE_BROWSER_XSS_FILTER = True
        django.middleware.security.SecurityMiddleware

When you're ready to start the DefectDojo server, type in this directory:

    python manage.py runserver

Note: If git cannot connect using the git:// protocol when downloading bower artifacts, you can run the command 
below to switch over to https://
          git config --global url.https://.insteadOf git://

**Comment by devGregA** [comment]
@opsdisk sorry that this issue popped up. Working to get everything fixed. We had a big feature push last week and with it a lot of issues. We are working on building up or CI testing to help prevent bugs like this in the future. I will update you shortly when we have this fixed.

**Comment by opsdisk** [comment]
No prob, I was the other guy on the video call this afternoon...just wanted to file it officially!

**Comment by devGregA** [comment]
Please see my latest comment here: https://github.com/OWASP/django-DefectDojo/issues/111

**Comment by opsdisk** [comment]
See setup.bash fix #115

This worked for me on an Ubuntu 14.04.3 x64 install.

Updated setup.bash (added libjpeg-dev) and changed the order of packages installed in setup.py (not sure if it matters, but it worked for me) and added packages uwsgi and watson.  

Had to comment out the last 3 lines in dojo/models.py as well

#watson.register(Product)
#watson.register(Test)
#watson.register(Finding)

**Comment by PrafulTamrakarRakuten** [comment]
pip install git+https://github.com/valentijnscholten/defectdojo_api/@acf0c0deb2dc5191d69f268412602bea5295a2e7

**Comment by opsdisk** [comment]
Appreciate the response @PrafulTamrakarRakuten , but I'm no longer using this software.  @devGregA - This ticket can be closed.
