### ISSUE TITLE
Import scanner results via the API

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#112]
I'd like the ability to upload scan results via the API. For example I'd like to automate running ZAP, generate the XML report and call the DOJO API to push in the findings from ZAP, Burp etc.

**Comment by mindtap** [comment]
This is going to be tricky: the TastyPie API framework does not deal well with file uploads[[1]](http://toastdriven.com/blog/2014/may/23/state-tastypie/)[[2]](https://github.com/django-tastypie/django-tastypie/issues/42)

**Comment by YSaxon** [comment]
This is going to be tricky: the TastyPie API framework does not deal well with file uploads[[1]](http://toastdriven.com/blog/2014/may/23/state-tastypie/)[[2]](https://github.com/django-tastypie/django-tastypie/issues/42)

**Comment by YSaxon** [comment]
I'm nearly done with this feature. (Hopefully...)

**Comment by aaronweaver** [comment]
@YSaxon That's great, I'm really looking forward to this. We are ready to try it test it as soon as you push it out.

**Comment by CCoffie** [comment]
@YSaxon I didn't see that you were working on this. I added the support myself in PR #168.

**Comment by devGregA** [comment]
@aaronweaver I think this is okay to close. Please let re-open if need be.
