### ISSUE TITLE
Report Filters Don't Show

### ISSUE THREAD

**Issue by tmsteen** [OWASP/django-DefectDojo#113]
After the clean install, in the report builder view, the filters do not show up.  The titles for each filter show up, but the dropdown/selectors do not.  I examined filter_snippet.html and it matches the current version.  If that is indeed the part that generates the filters. 

![image](https://cloud.githubusercontent.com/assets/8290250/18402024/2d8bb7e2-76a3-11e6-99e5-3127905fc154.png)

**Comment by devGregA** [comment]
Hi @tmsteen unfortunately I'm not able to replicate the issue. When you run `python mange.py runserver` from the django/defectDojo directory are there any errors in the console? Do you have NoScript enabled?

**Comment by devGregA** [comment]
Didn't hear back so closing. I this is most likely because you removed watson.
