### ISSUE TITLE
Soft Failure with OS X in setup.bash

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#116]
I get an 'illegal byte exception'
`MySQL user (should already exist): root
Password for user:
Database name (should NOT exist): gregtestingdb

mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Created database gregtestingdb.
tr: Illegal byte sequence
Leaving Django 1.8.10 requirement`

**Comment by crc32a** [comment]
Careful with those passwords in email.
