### ISSUE TITLE
Complete Django DB Support

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#125]
### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to use any of the official databases supported by Django (MySQL, Postgres, SQLite, and Oracle). We currently only support MySQL to leverage preloading efficiency requirements.

Implementation Requirements:

- [ ] Modify dojo/metrics/views.py to check settings.py and see which database has been selected.
- [ ] If MySQL is selected, continue to use the preloaded queries, otherwise use native django filters.
- [ ] Update setup.bash to accept input to select a database from the list above.

Resources:
https://docs.djangoproject.com/en/1.10/ref/databases/

**Comment by grendel513** [comment]
@devGregA postgres, sqlite, and other backends will mean looking into all the MySQL specific queries peppered throughout dojo.  MySQL is the only DB that allows for preloading and efficiencies we leverage especially for the query heavy metrics pages.  This is bigger than just settings.py entries.

**Comment by devGregA** [comment]
## Complete Django DB Support

### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to use any of the official databases supported by Django (MySQL, Postgres, SQLite, and Oracle). We currently only support MySQL to leverage preloading efficiency requirements.

Implementation Requirements:

- [ ] Modify dojo/metrics/views.py to check settings.py and see which database has been selected.
- [ ] If MySQL is selected, continue to use the preloaded queries, otherwise use native django filters.
- [ ] Update setup.bash to accept input to select a database from the list above.

Resources:
https://docs.djangoproject.com/en/1.10/ref/databases/

**Comment by narayanaditya95** [comment]
Please assign this issue to me.

**Comment by devGregA** [comment]
All yours! :)

**Comment by xandfury** [comment]
Use an ORM such as SQLAlchemy instead of MySQL. This would eliminate the need of maintaining separate support to various DBs

**Comment by devGregA** [comment]
Dojo now supports postgres, which was the main ask for the community. closing due to limited resources
