### ISSUE TITLE
URL Prefix usage breaks existing deployments

### ISSUE THREAD

**Issue by grendel513** [OWASP/django-DefectDojo#127]
@devGregA pulling from master and running app yields:

`AttributeError at /login
'Settings' object has no attribute 'URL_PREFIX'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/login?next=/
Django Version:	1.8.10
Exception Type:	AttributeError
Exception Value:	
'Settings' object has no attribute 'URL_PREFIX'
Exception Location:	/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages/django/conf/__init__.py in __getattr__, line 49
Python Executable:	/Users/jpaz/.virtualenvs/dojo/bin/python
Python Version:	2.7.12
Python Path:	
['/Users/jpaz/defect-dojo',
 '/Users/jpaz/.virtualenvs/dojo/lib/python27.zip',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-darwin',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-tk',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-old',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages',
 '/Users/jpaz/defect-dojo']
Server time:	Wed, 5 Oct 2016 11:00:30 -0500`

This is because the `urls.py` is using the new prefix setting without checking that it exists.

**Comment by devGregA** [comment]
@grendel513 this should be fixed. Please see my comment in latest PR.
