### ISSUE TITLE
Fixes URLs in reports.html & report_builder.html

### ISSUE THREAD

**Issue by mtesauro** [OWASP/django-DefectDojo#129]
Using: 
`$ grep -R -n "/reports/" dojo/*`

I found a couple of fixed paths which hurt the ability to shift Defect Dojo off the root of the web server to say "/dojo/" or whatever.  One of these below has been addressed in https://github.com/OWASP/django-DefectDojo/pull/124

**dojo/templates/dojo/reports.html**

```
dojo/templates/dojo/reports.html:133:                $.get("/reports/" + this.id + "/status", function (data, status) {
dojo/templates/dojo/reports.html:136:                        $('span#'+data.id).html("<a class='btn btn-primary btn-sm' href='/reports/[id]/download'>Download <span class='fa fa-download'></span></a> <a class='btn btn-sm btn-info' href='/reports/[id]/regen'>Regenerate <span class='fa fa-refresh'></span></a> <form method='post' action='/reports/[id]/delete' style='display: inline' class='form-inline form'>{% csrf_token %}<input type='hidden' name='id' value='[id]'/><button type='submit' class='btn btn-danger btn-sm report-delete'>Delete <span class='fa fa-trash'></span></button></form>".replace(/\[id\]/g, data.id));
dojo/templates/dojo/reports.html:144:                        $('span#'+data.id).html("<a class='btn btn-sm btn-warning'>" + data.status.charAt(0).toUpperCase() + data.status.slice(1) + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class='fa fa-exclamation-triangle'></i></a> <form method='post' action='/reports/[id]/delete' style='display: inline' class='form-inline form'>{% csrf_token %}<input type='hidden' name='id' value='[id]'/><button type='submit' class='btn btn-danger btn-sm report-delete'>Delete <span class='fa fa-trash'></span></button></form>".replace(/\[id\]/g, data.id));
```

or more easy to read:

dojo/templates/dojo/reports.html:133:                $.get(**"/reports/" + this.id + "/status"**, function (data, status) {

dojo/templates/dojo/reports.html:136:                        `$('span#'+data.id).html("<a class='btn btn-primary btn-sm'` href=**'/reports/[id]/download'**>`Download <span class='fa fa-download'></span></a> <a class='btn btn-sm btn-info' href='/reports/[id]/regen'>Regenerate <span class='fa fa-refresh'></span></a> <form method='post' `action=**'/reports/[id]/delete'** `style='display: inline' class='form-inline form'>{% csrf_token %}<input type='hidden' name='id' value='[id]'/><button type='submit' class='btn btn-danger btn-sm report-delete'>Delete <span class='fa fa-trash'></span></button></form>".replace(/\[id\]/g, data.id));`

dojo/templates/dojo/reports.html:144:                       ` $('span#'+data.id).html("<a class='btn btn-sm btn-warning'>" + data.status.charAt(0).toUpperCase() + data.status.slice(1) + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class='fa fa-exclamation-triangle'></i></a> <form method='post'` action=**'/reports/[id]/delete'** `style='display: inline' class='form-inline form'>{% csrf_token %}<input type='hidden' name='id' value='[id]'/><button type='submit' class='btn btn-danger btn-sm report-delete'>Delete <span class='fa fa-trash'></span></button></form>".replace(/\[id\]/g, data.id));`

**dojo/templates/dojo/report_builder.html**

```
dojo/templates/dojo/report_builder.html:46:        <form id="custom_report" class="hidden" action="/reports/custom" method="post">
dojo/templates/dojo/report_builder.html:170:                $.get('/reports/findings?' + $(this).serialize()).done(function (data) {
dojo/templates/dojo/report_builder.html:181:                $.get('/reports/findings'+link_href).done(function (data) {
dojo/templates/dojo/report_builder.html:191:                $.get('/reports/endpoints?' + $(this).serialize()).done(function (data) {
dojo/templates/dojo/report_builder.html:200:                $.get('/reports/endpoints').done(function (data) {
```

or more easy to read:

dojo/templates/dojo/report_builder.html:46:       ` <form id="custom_report" class="hidden" **`action="/reports/custom"** `method="post">
`

**Fixed with** https://github.com/OWASP/django-DefectDojo/pull/124/files#diff-b9ac55b429cf49fb93dce4265a1a247eL46

dojo/templates/dojo/report_builder.html:170:                **$.get('/reports/findings?'**` + $(this).serialize()).done(function (data) {`

dojo/templates/dojo/report_builder.html:181:                **$.get('/reports/findings'**`+link_href).done(function (data) {`

dojo/templates/dojo/report_builder.html:191:                **$.get('/reports/endpoints?'**` + $(this).serialize()).done(function (data) {`

dojo/templates/dojo/report_builder.html:200:                **$.get('/reports/endpoints')**`.done(function (data) {`

**Comment by devGregA** [comment]
Done
