### ISSUE TITLE
Deployment Buttons

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#138]
Support single click deploys for Heroku, Bitnami, etc.

**Comment by aaronweaver** [comment]
@devGregA Added DockerCloud One click installation.

**Comment by devGregA** [comment]
Hey Aaron when I click the button I get a 404, am I doing something wrong?

**Comment by devGregA** [comment]
It also looks like something is a little off in the readme. See 'Once Click Installations'

**Comment by aaronweaver** [comment]
Just logged out of dockercloud and got the 404. Apparently they don't redirect you to login. :( I'll put in line about logging in first before using the one-click installation.
