### ISSUE TITLE
Improved information on running Dojo in production

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#139]
uwsgi, gunicorn, nginx, etc

**Comment by a1ec** [comment]
@devGregA currently Dojo seems to be tied to MySQL, would be good if there was less coupling.
Also current set up using Django test server, a basic guide would be great for setting up with gunicorn, nginx etc. I'm slowly making progress, will advise if I can add some notes.

**Comment by mish24** [comment]
@devGregA I'll include this with #249
