### ISSUE TITLE
Severity Name Toggling

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#159]

**Comment by grendel513** [comment]
@devGregA Details?

**Comment by devGregA** [comment]
@grendel513 right now in the metrics 'severity' is displayed as s3-s0 instead of low-critical. Should we axe this? Or make it toggle-able?

**Comment by grendel513** [comment]
@devGregA - i see.  All the graphs (or most) do use the full severity name, it is the text based metrics that use the numerical severity value.  We can either show both "Critical (S0)" or we can have a toggle (javascript based) that can translate one to the other.

**Comment by devGregA** [comment]
Sent you a Slack message, but I think it should be togglable from the settings. What are your thoughts?
