### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#170]
Error creating a finding and updating an engagement: 

**Finding issue:**
Finding is created but the following error is returned: Finding' object has no attribute 'risk_acceptance'

`POST /api/v1/findings/ HTTP/1.1
Host: localhost:8000

{"product": "/api/v1/products/1/", "description": "Description", "reporter": "/api/v1/users/1/", "active": "true", "references": null, "date": "2016-11-01", "impact": "None", "verified": "false", "severity": "Critical", "title": "API Created", "engagement": "/api/v1/engagements/1/", "mitigation": "References", "test": "/api/v1/tests/1/", "cwe": 25}`

Response:
"error_message": "'Finding' object has no attribute 'risk_acceptance'

**Updating an Engagement:**

`PUT /api/v1/engagements/1/ HTTP/1.1
Host: localhost:8000

{"name": "Engagement Update Test"}`

Response:
`"/django-DefectDojo/dojo/api.py\", line 80, in form_args\n    pk = self._get_pk_from_resource_uri(rel_field, resource_uri)\n\n  File \"/django-DefectDojo/dojo/api.py\", line 63, in _get_pk_from_resource_uri\n    if not resource_uri.startswith(base_resource_uri):\n\nAttributeError: 'int' object has no attribute 'startswith'\n"}`

You can try these tests from here: https://github.com/aaronweaver/defectdojo_api/blob/master/tests/defectdojo_api_unit_test.py

python -m unittest -v tests.defectdojo_api_unit_test

**Comment by aaronweaver** [comment]
@grendel513 Would you mind taking a look at these API errors? Not sure if I'm missing something when I create or if the API has a bug.

**Comment by grendel513** [comment]
@aaronweaver - I'll take a look.  The second one is definitely a bug/misconfiguration, the first will take some digging around.

**Comment by aaronweaver** [comment]
Hi @grendel513 have you had a chance to review?

**Comment by devGregA** [comment]
bumping :) @grendel513

**Comment by grendel513** [comment]
I have a fork that i ma working on to address this, but i have not had the time to finish it up.

**Comment by devGregA** [comment]
https://github.com/OWASP/django-DefectDojo/issues/337 same issue

**Comment by devGregA** [comment]
@aaronweaver are you easily able to re-test this? 

https://github.com/OWASP/django-DefectDojo/blob/master/dojo/api.py#L493
I'm not sure when this change was made, but I'm curious if this is still an issue before I go tinkering.

**Comment by nabaaron** [comment]
We are all set here. I've updated the python api wrapper.
