### ISSUE TITLE
Create AdHoc Vulnerability Shortcut

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#174]
Add an option on the dropdown in Product to create an AdHoc finding. This would create a test called AdHoc Finding and take the user to the 'Create Finding Screen.'

![jira_test_product_integration](https://cloud.githubusercontent.com/assets/220838/20971782/b3f59a34-bc60-11e6-837b-8ce76c04966d.jpg)

**Comment by aaronweaver** [comment]
Also would need to create an engagement.

**Comment by devGregA** [comment]
I think we could also make this a swag issue. Thoughts @aaronweaver?

**Comment by devGregA** [comment]
## Create AdHoc Vulnerability Shortcut

### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to add a finding to a product from the product dropdown as shown above.

Implementation Requirements:

- [ ] Add a drop-down item to create a finding.
- [ ]when selected a finding form should be displayed.
- [ ] If the information is validated, a engagement and test should also be created as described above. If an  AdHoc test / engagement already exists, a new one should **not** be created. Instead the new finding should be added to the existing test / engagement.

**Comment by narayanaditya95** [comment]
I wish to tackle this problem.

What should the default engagement and the test look like?

**Comment by grendel513** [comment]
@aaronweaver @devGregA - do you think it would be better if the add new finding form in this process asks you what active Test to add it to and if no Tests exists then it asks you what to name the engagement and test?  I think i will have time to tackle this one this week.

**Comment by devGregA** [comment]
@grendel513 was going to use this issue as a training issue for the students that will be helping with the Dojo in July  if that is alright with you :), I will go through and label such issues as 'code sprint' so we don't duplicate efforts
