### ISSUE TITLE
Alphabetize the Test Type

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#175]
Alphabetize the Test Type dropdown.

![image](https://cloud.githubusercontent.com/assets/220838/20972231/3c87f864-bc62-11e6-8b6a-e85f2fc8f573.png)

**Comment by aaronweaver** [comment]
Complete, PR to follow shortly.

**Comment by devGregA** [comment]
hey @aaronweaver would you push up this PR if you have it ready? Or is it already in and this just needs to be closed?

**Comment by aaronweaver** [comment]
@devGregA let me check

**Comment by devGregA** [comment]
If not this would be great issue for new folks who want to contribute

**Comment by aaronweaver** [comment]
I know I finished it, just not sure if I pushed it.

**Comment by devGregA** [comment]
@aaronweaver  doesn't look like it made it.

**Comment by devGregA** [comment]
hey @aaronweaver I thought I saw this in your commit history for the jira changes, but it doesn't look like it has changed.
