### ISSUE TITLE
View number of findings by engagement

### ISSUE THREAD

**Issue by anakin1** [OWASP/django-DefectDojo#184]
To view findings for an engagement (including number of findings by severity), you currently need to click through each scan/test since only the total # is shown. It would be handy if you could view either the list of all findings, or at least # of findings by severity - either directly from the engagement screen or via a new metrics screen.

**Comment by devGregA** [comment]
@grendel513 Thanks! I really like this one.

**Comment by anakin1** [comment]
Love the graphs, thanks for including this.
