### ISSUE TITLE
add_tests missing 'Lead' input value

### ISSUE THREAD

**Issue by humor4fun** [OWASP/django-DefectDojo#194]
Unable to use the Engagements/Add_Test function, traceback attached.

![image](https://cloud.githubusercontent.com/assets/7505051/21901698/c94befa0-d8c6-11e6-9992-d23557aa5727.png)

I'm super unfamiliar with using github for contributing, but I'm working on finding the code fix for this and will post the relevant lines once I have done so.

**Comment by humor4fun** [comment]
Within /dojo/forms.py
```
class TestForm(forms.ModelForm):
+  lead = forms.ModelChoiceField(
        queryset=User.objects.exclude(is_staff=False),
        required=True, label="Testing Lead")
~ fields = ['test_type', 'target_start', 'target_end', 'environment', 'percent_complete', ''lead', 'tags']
```
That did the trick so that I can add tests, but it might not be the correct fix.

**Comment by devGregA** [comment]
@humor4fun I think this was fixed with a previous patch. Will you try running `git pull`?

**Comment by humor4fun** [comment]
My bad, issue was fixed in a patch I hadn't downloaded.
