### ISSUE TITLE
Jira Improvements

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#199]
- Delete button on Jira Conf from the global settings.
- Add support for Bug, Task etc
- Ability to add custom tags
- Ability to choose component type
- In lists show if an issue has been pushed to Jira
- Search by jira listings

**Comment by aaronweaver** [comment]
In PR (https://github.com/OWASP/django-DefectDojo/pull/202) the following was completed:

- Issue type now supported in global config, future PR will bring that down to the product level.
- List views now show the Jira link and the link to view opens in a new tab

**Comment by devGregA** [comment]
Hi @aaronweaver would you update progress from your PR today when you can?

**Comment by aaronweaver** [comment]
In PR (https://github.com/OWASP/django-DefectDojo/pull/226) the following was completed:

- Support for Component on the Product level
- Attachments are now uploaded to Jira
- Fixed a bug where engagement was looking for a Jira ID when one wasn't assigned to the product

**Comment by devGregA** [comment]
Hi @aaronweaver is the last requirement here 'Search by jira listings'?

**Comment by aaronweaver** [comment]
Yes, that's the last one. I close this one and create a new one with a reward.
