### ISSUE TITLE
Low Priv User Login Exception

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#201]
At URL:
http://127.0.0.1:8000/login
Client:Client credentials are used to log into application with a non-staff, non-superuser profile.

An exception is raised and the login process seems to halt at:
http://127.0.0.1:8000/metrics
However an authenticated session is created as navigating back and using the application works fine.

The issue seems to relate to a malformed SQL statement? Dumps and stack traces provided below:

The SQL query being generated is:
u'SELECT (SELECT IF(dojo_finding.mitigated IS NULL, DATEDIFF(CURDATE(), dojo_finding.date), DATEDIFF(dojo_finding.mitigated, dojo_finding.date))) AS "sql_age", (SELECT COUNT(*) FROM dojo_risk_acceptance INNER JOIN dojo_risk_acceptance_accepted_findings ON ( dojo_risk_acceptance.id = dojo_risk_acceptance_accepted_findings.risk_acceptance_id ) WHERE dojo_risk_acceptance_accepted_findings.finding_id = dojo_finding.id) AS "ra_count", "dojo_finding"."id", "dojo_finding"."title", "dojo_finding"."date", "dojo_finding"."cwe", "dojo_finding"."url", "dojo_finding"."severity", "dojo_finding"."description", "dojo_finding"."mitigation", "dojo_finding"."impact", "dojo_finding"."refs", "dojo_finding"."test_id", "dojo_finding"."is_template", "dojo_finding"."active", "dojo_finding"."verified", "dojo_finding"."false_p", "dojo_finding"."duplicate", "dojo_finding"."out_of_scope", "dojo_finding"."under_review", "dojo_finding"."review_requested_by_id", "dojo_finding"."thread_id", "dojo_finding"."mitigated", "dojo_finding"."mitigated_by_id", "dojo_finding"."reporter_id", "dojo_finding"."numerical_severity", "dojo_finding"."last_reviewed", "dojo_finding"."last_reviewed_by_id" FROM "dojo_finding" WHERE ("dojo_finding"."verified" = ? AND "dojo_finding"."severity" IN (?, ?, ?, ?, ?) AND "dojo_finding"."date" >= ? AND "dojo_finding"."date" < ? AND "dojo_finding"."out_of_scope" = ? AND "dojo_finding"."duplicate" = ? AND "dojo_finding"."false_p" = ? AND "dojo_finding"."verified" = ?) ORDER BY "dojo_finding"."numerical_severity" ASC, "dojo_finding"."date" DESC, "dojo_finding"."title" ASC'

See dump below:
OperationalError at /metrics

no such function: IF

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/metrics
Django Version: 	1.8.10
Exception Type: 	OperationalError
Exception Value: 	

no such function: IF

Exception Location: 	/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable: 	/django-DefectDojo/venv/bin/python
Python Version: 	2.7.10
Python Path: 	

['/django-DefectDojo',
 '/django-DefectDojo/venv/lib/python2.7',
 '/django-DefectDojo/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/django-DefectDojo/venv/lib/python2.7/lib-tk',
 '/django-DefectDojo/venv/lib/python2.7/lib-old',
 '/django-DefectDojo/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/django-DefectDojo/venv/local/lib/python2.7/site-packages',
 '/django-DefectDojo']

Server time: 	Mon, 23 Jan 2017 23:22:01 -0600

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/metrics

Django Version: 1.8.10
Python Version: 2.7.10
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'djangobower',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware')

Traceback:
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/django-DefectDojo/dojo/metrics/views.py" in metrics
  197.                                        relative_delta='months')
File "/django-DefectDojo/dojo/utils.py" in get_period_counts
  368.         for finding in findings:
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django_filters/filterset.py" in __iter__
  313.         for obj in self.qs:
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/query.py" in __iter__
  162.         self._fetch_all()
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/query.py" in _fetch_all
  965.             self._result_cache = list(self.iterator())
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/query.py" in iterator
  238.         results = compiler.execute_sql()
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  840.             cursor.execute(sql, params)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/utils.py" in __exit__
  98.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  318.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /metrics
Exception Value: no such function: IF

**Comment by devGregA** [comment]
Hi @a1ec thank you for your report! Will look into this today.

**Comment by devGregA** [comment]
Hi sorry @a1ec I got deterred by a family event. Will absolutely look into this on Monday.

**Comment by a1ec** [comment]
Thanks Greg. Update: setting the Staff flag in the user profile alleviates the issue. However, I wish to set up a low privilege 'Client' user that can only read a subset of the input data.

**Comment by devGregA** [comment]
Hi @a1ec, unfortunately I'm not able to reproduce the issue. Can you try with the latest code? Is there some step I could be missing?

**Comment by a1ec** [comment]
G'day @devGregA , I've done a `git pull` and I have the latest it seems.
Created another user with permissions below and access to the Product.
![image](https://cloud.githubusercontent.com/assets/17076802/22577945/137f0eb4-ea19-11e6-97cf-be95cf928297.png)

The same issue persists. Note sure yet what else I can try, open to suggestions.

**Comment by devGregA** [comment]
Hi @a1ec would you be up for a video meeting so I could see it first hand? If so what time zone are you in?

**Comment by a1ec** [comment]
Hi @devGregA, definitely! I am in AEDT, happy to convene when you can

**Comment by devGregA** [comment]
Hi @a1ec, how about Tuesday? I'm free any time after 10:00 AM - 5:00 PM AEDT. Shoot an email to greg.anderson@owasp.org and I'll setup a Google Hangout for whenever works for you.

**Comment by devGregA** [comment]
**OH** @a1ec are you using sqlite? I was looking back through you paste. Would it be possible to use maria or mysql instead?

**Comment by a1ec** [comment]
Yes I am using sqlite as part of the standard docker install, it may be sqlite specific.
Is it a big with the django ORM?
I was looking to use the production docker-compose environment but I have had issues running it).

**Comment by devGregA** [comment]
@aaronweaver I'm not very familiar with the Docker version. Could you look at this issue?

**Comment by aaronweaver** [comment]
@devGregA sure, I'll review

**Comment by devGregA** [comment]
@a1ec ah, nevermind don't change the DB just yet. I didn't realize this was for the Docker version. Aaron is looking into it. He is much more well-versed on the docker version than I am.

**Comment by devGregA** [comment]
hey @aaronweaver have you had a chance to take a look?

**Comment by a1ec** [comment]
Hi @aaronweaver @devGregA just wondering if there is any update? This issue hinders usability and presentation of the app, as some of our team think it's broken

**Comment by aaronweaver** [comment]
@devGregA Was the metrics page built specifically to go against MySQL? I do remember coming across this issue, it's only if you do anything on the metrics page, all other functionality works.

**Comment by devGregA** [comment]
@aaronweaver right now yes, I forgot about that. We preload some queries to improve performance. Why would an un-authed user be able to access it though while a staff user is not?

**Comment by devGregA** [comment]
** non-staff user

**Comment by aaronweaver** [comment]
I think what's happening is that it was the last URL visited so when you auth it's re-directing you to the metrics page which errors out. The login process worked correctly it's just the metrics page that errored out. I think for now what I'll do is just test to see if sqllite. At some point I'll see if it's worth writing it to support sqllite.

**Comment by devGregA** [comment]
I can throw in a statement to do a check on the settings and avoid the preloading if it is not sql. This would enable other db options such as postgres, etc. Will take this as an action for next week.

**Comment by grendel513** [comment]
@devGregA @aaronweaver - this is definitely because MySQL is not in use for this setup.  For 100% functionality, MySQL is required at this point.  Without the preloading in Metrics the pages are very slow and require a lot of sql queries.

**Comment by grendel513** [comment]
@devGregA @aaronweaver @a1ec - I found the issue and believe I have fixed it with pull request #305 - @a1ec can you please check once that pull request is merged?  You will need to update to Django 1.11 - see docs here: https://defectdojo.readthedocs.io/en/latest/upgrading.html#upgrading-to-django-1-11

**Comment by devGregA** [comment]
Closing due to stalled discussion. Believed to be fixed.
