### ISSUE TITLE
Report Builder: WYSIWYG Content does not allow report generation

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#209]
When adding a WYSIWYG content component to a Report, clicking the Save and Run button does not generate a report. Removing the component allows generation.

**Comment by devGregA** [comment]
@grendel513 do you mind taking this one?

**Comment by grendel513** [comment]
@a1ec - sorry for the delay on this - can you please provide the content you are adding in the WYSIWYG text area?

**Comment by a1ec** [comment]
@grendel513 to elaborate, if the WYSIWYG component is included, the 'Save and Run' button will have no effect, regardless of whether there is text in there or not. My environment is the development version with SQLite backend, in case that makes a difference.

**Comment by devGregA** [comment]
@grendel513 confirmed on ./setup.bash install

**Comment by devGregA** [comment]
@grendel513 this would be a great one if you have bandwidth :)
