### ISSUE TITLE
Finding: Add Note Exception raised 

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#210]
Adding a Note to a Finding results in an exception (performed with admin user).

Exception Type: DoesNotExist at /finding/4
Exception Value: JIRA_PKey matching query does not exist.

Please see exception details at:
http://dpaste.com/1B99H25

**Comment by devGregA** [comment]
@aaronweaver would you like this one or do you want me to take it?

**Comment by aaronweaver** [comment]
@devGregA I can take it. @a1ec are you using Jira?

**Comment by a1ec** [comment]
@aaronweaver Confirming I am not using JIRA.

**Comment by aaronweaver** [comment]
@devGregA @a1ec I pushed the fix, please verify when you can. Thanks

https://github.com/OWASP/django-DefectDojo/pull/214

**Comment by a1ec** [comment]
@aaronweaver @devGregA Tested Note Add with admin and low priv user, confirmed working. Thank you.
