### ISSUE TITLE
Vulnerable Findings List: not able to access with authorized user

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#212]
While logged in as an active user without staff or admin privs, attempting to access a vulnerable endpoint list results in a prompt for login:
http://10.90.80.73:8000/login?next=/endpoint/vulnerable%3Fproduct%3D1

![image](https://cloud.githubusercontent.com/assets/17076802/22413453/06ac6142-e70c-11e6-9664-843ab6f1f6e2.png)

This is unexpected, as the product is in the user's Authorized Products list. There is also no message as to why access is denied.

**Comment by devGregA** [comment]
Hi @a1ec I also can't reproduce this one.

**Comment by devGregA** [comment]
Hi @aaronweaver this is the other one that doesn't seem to be present in the non-docker version.

**Comment by devGregA** [comment]
Hi @grendel513 I believe this one is specific to docker.

**Comment by a1ec** [comment]
@devGregA Confirming I have pulled latest code and switched to MySQL from SQLite.
Also environment is not docker. User is non-staff.
Picture of the offending link:
![image](https://cloud.githubusercontent.com/assets/17076802/23503350/8640b5f2-ff8f-11e6-8044-5ed94b38934e.png)

Also, I can see the hosts in question if I follow the Open Findings link, so the authorisation is a little confusing. I'm confused, is an authorised user of an engagement (but not staff / admin) not permitted to see the hosts?

**Comment by a1ec** [comment]
Although above issue remains, clicking the Endpoint Report link within the button pictured presents the expected affected endpoints:
![image](https://cloud.githubusercontent.com/assets/17076802/23592859/46a7f0a8-025b-11e7-9886-ab6e101a48a2.png)  

![image](https://cloud.githubusercontent.com/assets/17076802/23592880/9b46f082-025b-11e7-9d2e-c22261acf17a.png)

**Comment by ac-mercury** [comment]
@devGregA @aaronweaver @grendel513
Cloned latest repo into a clean environment this morning and confirm that issue persists. What information can I provide to you in order to troubleshoot?

**Comment by a1ec** [comment]
@devGregA @grendel513 Interesting you couldn't recreate... this was caused by decorator in dojo/endpoint/views.py:
```
@user_passes_test(lambda u: u.is_staff)
def vulnerable_endpoints(request):
....
```
IMHO User should not have to be staff to view vulnerable endpoints.
Works as expected after commenting out above decorator on my local version. Is this something that you would consider incorporating into upstream dojo master branch?

**Comment by grendel513** [comment]
I think that is a start.  If removing that user staff requirement, then the filter has to make sure the user is authorized for the products that own the endpoints.  Otherwise users will be able to see all endpoints - which is also not correct.

~jay
