### ISSUE TITLE
Migrate application level functionality from settings.py to the database

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#215]
There are several application level settings that should move to an application configuration page within DefectDojo. This will make it easier for people to review the settings and understand how DefectDojo is configured. Candidates for moving:

- Jira Enabled
- De-Dupe
- Mail Server
- Time Zone
- S_FINDING_SEVERITY_NAMING
- URL_PREFIX

**Comment by grendel513** [comment]
+1

**Comment by devGregA** [comment]
I'm good with making this is a swag issue if y'all are.

**Comment by patriknordlen** [comment]
Meta question that's possibly OT here, so bear with me - what implications do the labels here have? Does "Code Sprint" mean this is part of an upcoming spring with assigned developers who will work on this? I'm interested in trying to tackle this but if someone is already looking at it it's better if I do something else :)

**Comment by devGregA** [comment]
Hi @patriknordlen, 'swag rewards' means you get some Dojo swag when we do the next order (shirt and stickers). '1.2 Release' are issues we're hoping to complete before AppSec USA.  'Code Sprint' refers to the OWASP Code Sprint https://www.owasp.org/index.php/OWASP_Code_Sprint_2017, where students will assist with OWASP projects. Feel free to take this one though :). There is plenty of issues :joy, for this issue, I would suggest implementing with a single model e.g. 
`Class DojoSettings(models.Model):
    dedupe = models.BooleanField(default=False)
    .....
   etc
`
then I would just do a single form made available via the collapsable menu.

<img width="575" alt="screen shot 2017-06-30 at 6 31 35 pm" src="https://user-images.githubusercontent.com/4741312/27757039-b2fa85b4-5dc2-11e7-8a26-6266ee2ba4bc.png">

If you need help don't hesitate to ask! Always happy to help contributors come up to speed :)

P.S I should / will do a write-up on labels.

**Comment by patriknordlen** [comment]
Thanks for the info! I got something working in my fork that's build pretty much the way you're suggesting, just finishing up and will create a PR... :)
