### ISSUE TITLE
NMAP scan results import

### ISSUE THREAD

**Issue by bobdob42** [OWASP/django-DefectDojo#218]
could DefectDojo support Import of NMAP scan results, similar to Nessus or Burp XML
The nmap scan results would be in .XML format https://nmap.org/book/output-formats-xml-output.html

**Comment by devGregA** [comment]
Hi @bobdob42 we haven't supported nmap as a vulnerability scanner in the past because we didn't feel that open ports equal vulnerabilities. If you're using the  nmap plugins that is different, but we do support nmap / port scans http://defectdojo.readthedocs.io/en/latest/features.html#port-scans

**Comment by bobdob42** [comment]
Hi Greg
was thinking in terms of extending that "port-scans" feature, the DefectDojo server may not have access to the same parts of the infrastructure to allow those scans or the scans maybe run by a 3rd party and we want to import the results.

**Comment by devGregA** [comment]
@bobdob42 ah great point. Definitely would be a great enhancement. Unfortunately, I'm not sure when I'll be able to get to it due to my backlog.

**Comment by patriknordlen** [comment]
I have a working prototype for this, it essentially creates informational findings for each open port. Issuing a PR shortly.

**Comment by devGregA** [comment]
@bobdob42 done :) courtesy of @patriknordlen
