### ISSUE TITLE
PDF Report generation issue on Defect Dojo "Still Running "

### ISSUE THREAD

**Issue by sandeshM27** [OWASP/django-DefectDojo#224]
We had install all the packages and followed all the step to achieve the PDF generation of Defect Dojo but still Report generation button show us "Running" status.. Kindly help us and give right solution.. we are eagerly waiting for your response.

**Comment by devGregA** [comment]
Hi @sandeshM27 did you follow these steps? http://defectdojo.readthedocs.io/en/latest/features.html#reports

**Comment by devGregA** [comment]
Closing, haven't heard back from @sandeshM27, will reopen if needed.

**Comment by planitlady** [comment]
Hi I would like to reopen this issue. I was able to do the steps indicated in - http://defectdojo.readthedocs.io/en/latest/features.html#reports.

However, PDF still keeps on running non-stop without generating anything.

These are the responses from dojo worker:
```
celery -A dojo worker -l info --concurrency 3
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0
```
Celery Beat
```
celery beat -A dojo -l info
celery beat v4.2.1 (windowlicker) is starting.
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 4256)
```

Any suggestions?

Thanks!

**Comment by deepaksadashiv92** [comment]
@planitlady : We are facing the same issue, were you able to fix this issue and any suggestions if you did?
Thanks!

**Comment by LeonardoNve** [comment]
The same question here. Everything installed, including wkhtmltopdf:

> [root@DEFECTDOJO settings]# which wkhtmltopdf 
> /usr/bin/wkhtmltopdf
> [root@DEFECTDOJO settings]# grep wkhtml settings.py
> \# wkhtmltopdf settings
> WKHTMLTOPDF_PATH = '/usr/bin/wkhtmltopdf'

But when generating a PDF report it remains `Running`, tested in production and with `Debug = True`

**Comment by PreenaPrakash** [comment]
Hi,
Same problem here. Anybody got solutions?
Thanks in Advance.

**Comment by dayal18** [comment]
How did you guys even get till there, I don't even see PDF in the drop-down.. any suggestions?

**Comment by Oxima69** [comment]
Hello,
Here the same problem. Anybody got solutions?
Thank you very much.

**Comment by immewnity** [comment]
Adding to the echo chamber - same errors here.

**Comment by PreenaPrakash** [comment]
Hi,
please follow these steps:
1)	ADD pdf option in forms.py
```
`class CustomReportOptionsForm(forms.Form):
	    report_type = forms.ChoiceField(required=False, choices=(('AsciiDoc', 'AsciiDoc'),**('PDF', 'PDF')**))
`
```
2)	**Reports/views.py**
def custom_report(request):
async_custom_pdf_report(report=report,
                                          template="dojo/custom_pdf_report.html",
                                          filename="custom_pdf_report.pdf",
                                          host=host,
                                          user=request.user,
                                          uri=request.build_absolute_uri(report.get_url()),
                                          finding_notes=finding_notes,

Remove the delay function in the async_custom_pdf_report

3) Then you might get a path error like below:
```
Traceback (most recent call last):
  File "/opt/dojo/local/lib/python3.6/site-packages/pdfkit/configuration.py", line 21, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/wkhtmltopdf'
```

solution:   
Download wkhtmltopdf from this site https://wkhtmltopdf.org/downloads.html and install it.
Eg: for ubuntu 18 download 18.04 (bionic) 	amd64

by this make sure the wkhtmltopdf is in the specified path.

4) If you came across the following error.

django.db.utils.IntegrityError: (1048, "Column 'task_id' cannot be null")

make the following changes:

In tasks.py, 

```
def async_custom_pdf_report

 try:
        report.task_id = 1 
        report.save()

give the repor.task_id as 1.
```

Try to create a pdf now.
Hope this helps ..
