### ISSUE TITLE
Metric Counts  --> Open Findings does not show all finding

### ISSUE THREAD

**Issue by owaspwilton** [OWASP/django-DefectDojo#225]
when viewing the open findings in metrics ,  the table does not show all the findings.  In my case we have a project with 1 Critical and one with 2 Critical , it shows the project with two Critical , but it does not shows the project with 1 Critical
Here is the way to get to the link:
Home page ---> Metrics --->  Product Type Metrics --> Opened Findings.

**Comment by devGregA** [comment]
@grendel513 @aaronweaver I have verified this issue. For some reason it is only showing the open findings for one product. (see pythonanywhere) Thank you @owaspwilton for the report!

**Comment by grendel513** [comment]
@devGregA - it has to do with the date filter.  it defaults to the last 30 days...if you change it to any date the other products show up.  No bug here, that i can see

![image](https://cloud.githubusercontent.com/assets/233694/23224941/d3361d66-f8f5-11e6-8446-f86ee7c1b6db.png)

![image](https://cloud.githubusercontent.com/assets/233694/23224958/e1003864-f8f5-11e6-9f9e-795498d9accf.png)

**Comment by devGregA** [comment]
OH great catch! thanks @grendel513. @owaspwilton please see @grendel513's comment
