### ISSUE TITLE
Status Updates via Slack / Email

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#228]
### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to configure slack / email notifications for issues.

Implementation Requirements:

- [ ] Create a configuration page that has a checkbox matrix to assign when notifications will be sent out.
- [ ] Integrate with slack APIs to push issues to a **channel**
- [ ] Use the email integration present with scan profiles to send notifications via this new system.
- [ ] Add documentation to the /docs folder.

Resources:
Slack Documentation:  https://api.slack.com/custom-integrations

**Comment by patriknordlen** [comment]
I worked on this tonight and have notification settings and slack integration working. Next up are mail and docs, as well as adding support for notifications for more events.
