### ISSUE TITLE
Enhancements to Tagging

### ISSUE THREAD

**Issue by humor4fun** [OWASP/django-DefectDojo#236]
This might be multiple enhancements. The Tagging features exist only on "Product" and appear only on the Product View and Edit pages. I propose the following enhancements to "Tagging" as a whole:

- Expanded tagging: ability to place tags on endpoints, engagements, tests, maybe even findings
- Search: use tags to search in the universal search box. Results should identify what type of data the tag appeared on (separated by UI widget, or by a table field) with a link to view that object page.
- Auto-search: clicking on a tag (anywhere they are displayed) should perform a "search: tag=XYZ" function
- Inheritance: if a tag is applied to an Engagement, it also shows up on the Product (perhaps in a different color to show inheritance, maybe with a super-script number to show count of inherited instances of that tag)
- Metrics: Report on tags in a dashboard view or a "word cloud" kind of thing to show the list of tags and how many times they appear, perhaps broken down into the type of thing they appear on (Tag A appears on Products 7 times, Engagements 3 times and Tests 57 times)

**Comment by aaronweaver** [comment]
@humor4fun Just pushed a PR to bring out tagging to the various views. Tagging was on finding, engagement, endpoint etc. just not obvious that it was there. Added tags to each view and simple search will categorize where the tag was found. 

PR: https://github.com/OWASP/django-DefectDojo/pull/242

**Comment by devGregA** [comment]
I'm going to go ahead and close. Feel free to reopen if necessary.
