### ISSUE TITLE
Engagement with open ended duration

### ISSUE THREAD

**Issue by bwu-tang** [OWASP/django-DefectDojo#246]
We'd like to create a recurring weekly vulnerability scan, but the end date on an engagement is a required field. It would be nice to get a recurring engagement type rather than either creating a new engagement for each scan, or setting a set ending timeframe.

**Comment by devGregA** [comment]
Hi @bwu-tang you can change this by adding `required=False` to https://github.com/OWASP/django-DefectDojo/blob/master/dojo/forms.py#L453

@grendel513 @aaronweaver please let me know if you think this should be considered as a change to core. I do not see the advantage at this time.

**Comment by jonny64** [comment]
Hi!

End date of engagement is still required field.

Our use case: integration defectdojo into workflow, first scan, tons of warnings.

Could you please explain how to use defectdojo on weekly CICD scan basis? Should we create a new engament each time?

If we do so after 4 weekly scan dashboard reports of 400 findings total for 100 findings. They are duplicates, there are still 100 active findings.
