### ISSUE TITLE
Associate multiple products to engagement

### ISSUE THREAD

**Issue by bwu-tang** [OWASP/django-DefectDojo#247]
We'd like the ability to add multiple products to a particular engagement. For example, a vulnerability scan that might hit infrastructure on multiple products, or a bug bounty program across multiple products.

**Comment by aaronweaver** [comment]
@bwu-tang Thinking through this and it would break the existing database model quite a bit to allow multiple products on an engagement. Would it work if we allowed a finding to be re-assigned to the appropriate product? @devGregA do you agree with the approach?

**Comment by bwu-tang** [comment]
Perhaps there is a way to clone a finding and assign to multiple products?

There might be legitimate cases to have a single finding (maybe a vulnerability in a library) that is used across multiple products and different teams need to coordinate to update.

**Comment by aaronweaver** [comment]
I could see that use case, so support ability to assign to multiple products and / or move the finding out from a product.

**Comment by devGregA** [comment]
I think this ties into https://github.com/OWASP/django-DefectDojo/issues/366 @bwu-tang can you share your thoughts on if this meets your needs? Can discuss more to clarify 366

**Comment by devGregA** [comment]
closing tracking through https://github.com/OWASP/django-DefectDojo/issues/366
