### ISSUE TITLE
Bulk finding update - Poor error message: Severity is only required field

### ISSUE THREAD

**Issue by Greenjam94** [OWASP/django-DefectDojo#248]
![screen shot 2017-03-20 at 1 17 10 pm](https://cloud.githubusercontent.com/assets/5766832/24112375/b4d3f756-0d6f-11e7-970f-d8b5779c69c0.png)

I imported issues from Fortify on Demand CSV. There is a severity for all of the issues I imported. However, there's no description, mitigation, or impact fields. When I try to bulk edit to verify all of them, I get the attached error message.

When editing the finding directly, I can see each field is required. The error message just needs to be more accurate maybe something like "Unable to process bulk update. Required fields are invalid, please update individually".

**Comment by devGregA** [comment]
Hi @Greenjam94 it looks like this is where the error message is located https://github.com/OWASP/django-DefectDojo/blob/master/dojo/test/views.py#L406 would you like to do the PR? :)

@grendel513 anything to add here on why this message is the way it is?

**Comment by grendel513** [comment]
No, looks like a good catch. Thanks!

**Comment by devGregA** [comment]
fixed.
