### ISSUE TITLE
Consolidate Docs Info to ReadtheDocs

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#249]
### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, The information on the GitHub docs / wiki should be consolidated to our ReadtheDocs Site. To get the swag reward, this must be done to the satisfaction of the maintainers. Upon completion the docs / wiki will be removed to instead redirect to our ReadtheDocs page.

**Comment by mish24** [comment]
@devGregA I want to work on this! Please tell me if it's alright? :)
