### ISSUE TITLE
Unable to Create Finding from Template

### ISSUE THREAD

**Issue by StephenNickle** [OWASP/django-DefectDojo#254]
I recently installed Defect Dojo following the instructions in the getting started guide. It seems to be working correctly except that I'm unable to create a finding using an existing template. I am able to create a new template and I'm able to create a new finding. I am running Red Hat Enterprise Linux Server 7.3(Maipo) on a VM.  I appreciate any help you can provide.

Steps to Reproduce:
1. Create new template or create new template from finding.
2. From within a test, click the new finding drop-down and select Finding from Template.
3. For an existing template, click either Use this Template or the Name of the finding. Clicking either one produces the error shown below.
![image](https://cloud.githubusercontent.com/assets/13263428/24316369/5b1c1f00-10bb-11e7-8336-c5570c02b167.png)

Environment:

Request Method: GET
Request URL: http://*********************/test/14/add_findings/10

Django Version: 1.8.10
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'djangobower',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/opt/django-DefectDojo/dojo/test/views.py" in add_temp_finding
  355.                    'jform': jform,

Exception Type: UnboundLocalError at /test/14/add_findings/10
Exception Value: local variable 'jform' referenced before assignment

**Comment by devGregA** [comment]
thanks @StephenNickle will have this fixed this week

**Comment by devGregA** [comment]
believe to be fixed, please feel free to reopen if it isn't for you.

**Comment by StephenNickle** [comment]
This fixed the issue. Thank you so much for your help!
