### ISSUE TITLE
Vulnerability in Pillow 3.3.0 of OWASP/django-DefectDojo

### ISSUE THREAD

**Issue by curphey** [OWASP/django-DefectDojo#265]
Your **Pillow 3.3.0** library, a direct dependency in your **OWASP/django-DefectDojo** repository, is subject to vulnerability [SID-2843: Sign Extension in Storage.c](https://www.sourceclear.com/registry/vulnerabilities/2843).

A direct dependency is a library that is specified in your project’s setup.py.  A vulnerability in a direct dependency can be fixed by updating the version of the library in your project and rebuilding it.

This issue was fixed in version 3.3.2. That version is currently considered safe, so we suggest that you upgrade to version 3.3.2.

Be sure to build, test, and re-scan your project to ensure this fix has been successful.

##### setup.py
```python
...
pillow == 3.3.2
...
```

For more information on this vulnerability, please visit the [SourceClear Registry](https://www.sourceclear.com/registry/vulnerabilities/2843).

**Comment by mtesauro** [comment]
I took the time to look at all the Source Clear issues entered against Dojo back on April 6th- full details are in this [Google Doc](https://docs.google.com/document/d/1Z0lJPIR1x2D0Q2_XqfYh-ZPvuK8q3gcQNxbTtgzRN38/edit?usp=sharing).  I figured I should actually add the results to the issues so any of our users can see that we take these things seriously.

Overall for all the issues, I found:
- 3 False Positives
- 1 Duplicate
- 3 Already planned updates of Python modules which we're either not vulnerable or maybe in certain edge cases.

For this specific issue, the TLDR is: We should probably update Pillow and test to make sure Doj is working as expected - it's a dependency of [django-imagekit](https://pypi.python.org/pypi/django-imagekit). At worst, you'd have to be an authenticated user to trigger the issue, though its not 100% clear Dojo is vulnerable based on how we used django-imagekit.
