### ISSUE TITLE
User can enter a greater start date than the end date.

### ISSUE THREAD

**Issue by mish24** [OWASP/django-DefectDojo#271]
![screenshot from 2017-04-14 02-34-29](https://cloud.githubusercontent.com/assets/24610197/25024313/0eca8de8-20bb-11e7-8c30-a9bc77fa3cdd.png)

Here the end dates for engagements and tests are allowed to be before the start dates. Shall we add this as an issue? Of course, genuine users won't do this, but a proper message must be shown, right?

**Comment by mish24** [comment]
Also, the finding dates must be within the test start and end dates.

**Comment by devGregA** [comment]
confirmed
