### ISSUE TITLE
Unauthorised User can view Details of Product

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#278]
I have non-admin user 'client' that is only authorised for the Products:  
ACME-Co/Infrastructure
BBSNet/External-Network  
When logging in with client, the following Products are listed.  
  
![image](https://cloud.githubusercontent.com/assets/17076802/26083404/004940f8-3a19-11e7-8b39-39baf8763456.png)

When visiting /metrics view, the following is available:  
![image](https://cloud.githubusercontent.com/assets/17076802/26083496/92273a2a-3a19-11e7-9d0b-169ccb082016.png)

Tesla-Inc/Infrastructure is visible to user client, who has no authorisation for the Product.

**Comment by devGregA** [comment]
Hi @a1ec they can't view the product info correct?

**Comment by devGregA** [comment]
Hi @a1ec I'm pretty positive that this is intended in the current state. We allow any authorized user to view metrics, but not the vulnerability details. I think this touches are the larger issue that we should redo permissions to be more of an access matrix

**Comment by a1ec** [comment]
Hi @devGregA if this is the current intended behaviour, a reimplementation would be desirable.  
In the context of a client with no relation to other products (belonging to other clients), all of which are sensitive by nature, it is more suitable for them to have zero knowledge of other Products.  
This would also be valid for teams within the same organisation working on different Products.
    
Currently, attempting to access the unauthorised Products results in a login prompt but as I am also having authentication problems with Issue #212, I am not sure which issue this behaviour is a result of.

**Comment by devGregA** [comment]
Agreed, the original thought was data for teams within the same company, but I would like to expand the permissions to make it more it an easier option for consultants.

**Comment by a1ec** [comment]
@devGregA sorry, realised that I do get the appropriate 403 hand slap when attempting to view, that is working as intended :)  
I will take a look at the code today.

**Comment by a1ec** [comment]
@devGregA  
There is an issue we've come across we're an unauthorised user can bypass some access controls to view details of a forbidden Product's findings.
Example below: user 'client' is authorised to view Products 1 and 2, Product 3 is admin only. Client is not staff and not super user.  

Logged in as 'client':
mysite.com/product/3 - returns 403
mysite.com/product/3/ - returns 404
**mysite.com/product/3/findings - returns 200**

Note the BBSNet in the navigation bar in the pic:
![image](https://cloud.githubusercontent.com/assets/17076802/26094953/2b6bcbfc-3a5f-11e7-83ee-a79c12a2d000.png)
Please advise if you can reproduce this issue.

**Comment by devGregA** [comment]
It looks like this stems from:
https://github.com/OWASP/django-DefectDojo/blob/master/dojo/finding/views.py#L67

@cneill @grendel513  any idea why that extra filter exists?

**Comment by a1ec** [comment]
@devGregA @cneill @grendel513 Additionally, the /metrics view includes metrics for Products the user is not authorised for, which is related, unexpected behaviour IMHO. Should I open a separate issue for that?

**Comment by grendel513** [comment]
@devGregA It is not an extra filter.  It is the instantiation of a Filter object OpenFindingFilter.  It determines what query have been chosen by the user on the filter form for that particular listing.  It takes the original queryset "filters" as a starting point and then filters it based on what has been chosen.

I think most of these views need to have a check to make sure the findings requested are in fact a part of a product that the user has access to.

**Comment by devGregA** [comment]
@grendel513 @a1ec I'm going to spend more time testing this, but I do not believe there is a bug.  We do not have a decorator on open findings, but we do apply specific filters based on whether or not a user is authorized. So, a 200 response would be expected. Will do more thorough testing on Monday.

**Comment by patriknordlen** [comment]
There's a similar issue with the findings widget in the custom report builder. I've solved it in a local branch by adding a custom qs property on the ReportAuthedFindingFilter, but not sure how the filter is supposed to be used in the first place...there's an attempt to do something similar here, I think: https://github.com/OWASP/django-DefectDojo/blob/a5b333d9cd381d4c684444638ceeaf0f0af38417/dojo/filters.py#L753

...but I don't know if it's doing something else altogether and I don't understand what, or if it's an attempt to filter out findings that doesn't work :)

**Comment by devGregA** [comment]
Found the issue. Believe to be fixed. @patriknordlen please open a second issue to document if necessary :)

**Comment by patriknordlen** [comment]
'My' bug still present, so opening a new issue for that.
