### ISSUE TITLE
PDF Reports Won't Generate

### ISSUE THREAD

**Issue by TommyJ1994** [OWASP/django-DefectDojo#285]
When you try and create a PDF report, it remains on the status 'Running' endlessly. 

ASCII-Doc report generation works without any issues.

Running on latest Master.

OS: Ubuntu 16.04

**Comment by devGregA** [comment]
Hi @TommyJ1994  is celery running http://defectdojo.readthedocs.io/en/latest/features.html#reports? There are a couple additional steps for reports. In the root directory of the project there is  reports.sh script. Running  `sudo sh reports.sh` will install all the linux package dependencies. Next `pip install pdfkit'. Change the WKHMTL path in `dojo/settings` to the result of  `which wkhmtltopdf`. Finally run `celery -A dojo worker -l info --concurrency 3`

**Comment by TommyJ1994** [comment]
Working now Thanks.
