### ISSUE TITLE
Guidance on ENABLE_DEDUPLICATION

### ISSUE THREAD

**Issue by professorgrumps** [OWASP/django-DefectDojo#288]
This is more of a general usage question, not sure where the best place to voice it, so here it is :-)
I am trying to use the docker image referenced here: 
http://defectdojo.readthedocs.io/en/latest/getting-started.html?highlight=docker 

I am trying to start the image with the ENABLE_DEDUPLICATION feature on

I have tried the following: 
`docker run -d -p 8999:8000 appsecpipeline/django-defectdojo bash -c "export ENABLE_DEDUPLICATION=True && export LOAD_SAMPLE_DATA=True && bash /django-DefectDojo/docker/docker-startup.bash"`

As well as a hail-mary of trying to overwrite the settings file before starting:
`docker run -d -p 8999:8000 appsecpipeline/django-defectdojo bash -c "sed -i  's/ENABLE_DEDUPLICATION = False/ENABLE_DEDUPLICATION = True/g' /django-DefectDojo/dojo/settings.dist.py && export LOAD_SAMPLE_DATA=True bash /django-DefectDojo/docker/docker-startup.bash"`

But DDJ does not seem to mark anything as a duplicate. 
Side note: my test case is essentially re-importing the same ZAP scan to simulate how DDJ identifies and handles duplicates - if I am understanding the feature correctly, the entirety of one of the scans should report back as duplicate, and I should see a "a list of deduplicated findings is added to the engagement view." I do not see this view :-(

Therefore, I guess my questions are: 
1) What is the preferred method to enable deduplication in the local docker image? 
2) Is there any way thru DDJ's UI that I can verify that the ENABLE_DEDUPLICATION feature is on?
3) Is the test case of simply re-importing the same ZAP scan valid for this feature?
4) Is there any further documentation on using the deduplication feature other than here? http://defectdojo.readthedocs.io/en/latest/features.html?highlight=deduplication

Gentle mention to @aaronweaver 
Thanks in advance, and if there is a better forum for such questions please let me know.

**Comment by devGregA** [comment]
Hi @professorgrumps glad to hear things worked out with ZAP! Aaron is definitely the docker expert. I will look into this though.

**Comment by professorgrumps** [comment]
thanks @devGregA for the previous assistance! any other help with the docker image would be appreciated, as you mentioned, gently mentioning @aaronweaver.

**Comment by devGregA** [comment]
Hi @professorgrumps is the regular install a viable option by chance?

**Comment by devGregA** [comment]
Or what about using the attach command?

**Comment by devGregA** [comment]
Closing due to no response.

**Comment by professorgrumps** [comment]
@devGregA sorry for the delay - yeah, this can be closed.
We're going to attempt a real install and see if we have a similar issue 
thanks!
