### ISSUE TITLE
Blank endpoint name entry with Nessus import 

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#289]
An additional blank endpoint entry is entered into dojo when performing a Nessus import. This endpoint has no text associated and there is no link through which to delete the entry.  
A screenshot of the Nessus UI scan results prior to export:

![image](https://cloud.githubusercontent.com/assets/17076802/26436101/68f4ecc0-4157-11e7-94a2-22f9bd6b6783.png)

After the import into dojo:

![image](https://cloud.githubusercontent.com/assets/17076802/26436150/cc036d78-4157-11e7-8f05-9e8b1e9f5e0a.png)

Should endpoint contain at least a hostname to be valid? 
```
class Endpoint(models.Model):
...
    host = models.CharField(null=True, blank=True, max_length=500,
...```

**Comment by grendel513** [comment]
@a1ec - thanks for letting us know!  Any way you can provide us with a sample Nessus report you are using? I want to make sure I am using the same test file you are when looking into this.

**Comment by a1ec** [comment]
G'day Jay, sorry I don't have it handy but I'll try and dig it up.
I'm confident that if you import a quick scan using Nessus Home on a private network with a couple of hosts, the issue may appear.

**Comment by devGregA** [comment]
thanks @a1ec will check it out first thing next week.

**Comment by devGregA** [comment]
@a1ec this zip appears to be password protected.

**Comment by a1ec** [comment]
I'm sorry about that, try the attachment below.
[test-nessus-scan.zip](https://github.com/OWASP/django-DefectDojo/files/1155004/test-nessus-scan.zip)

**Comment by grendel513** [comment]
@a1ec @devGregA - I was able to verify this issue.  I will work on solution asap.

**Comment by devGregA** [comment]
hey @grendel513 was going to have @devEricA do this one if you haven't already started

**Comment by grendel513** [comment]
@devGregA i am all done with it :( - pull request on its way
