### ISSUE TITLE
Veracode Import Doesn't Recognize Mitigation Status

### ISSUE THREAD

**Issue by jordanpotti** [OWASP/django-DefectDojo#290]
Issues that are mitigated in Veracode aren't recognized by DefectDojo. They import and show up as not mitigated. The workaround is to go back into each one and select "False Positive".

**Comment by devGregA** [comment]
Hi @jordanpotti could you provide a sample scan so I can correct this?

**Comment by jordanpotti** [comment]
I am working on getting a sanitary scan for you to test with. I have however just issued a pull request with added support to fix this problem.

**Comment by jordanpotti** [comment]
This was resolved with my last pull.
