### ISSUE TITLE
Bulk actions on Products, Engagements and Findings

### ISSUE THREAD

**Issue by naumek** [OWASP/django-DefectDojo#295]
Hello,
is it possible to add Bulk Edit option for Products and Engagements (mostly bulk remove)?

**Comment by grendel513** [comment]
@naumek - thanks for reaching out.  Bulk delete functionality is already available using the Django admin interface.  I don't believe it is necessary to duplicate those efforts within DefectDojo.

We did however, some time ago, add the ability to bulk edit some attributes of a Finding.  You can see that functionality in the view test page: 

![screen shot 2017-06-23 at 5 20 12 pm](https://user-images.githubusercontent.com/233694/27502231-4c3ca7ce-5838-11e7-8ebf-b1aa08f0372d.png)
