### ISSUE TITLE
PDF Report Cover Generation failure behind nginx

### ISSUE THREAD

**Issue by a1ec** [OWASP/django-DefectDojo#298]
I've set up nginx reverse proxy with dojo so that users require client-side certificates and the site is not open to the world, reducing chances of a compromise in case of a vulnerability with dojo / django.

Currently generating a cover for PDF reports calls URL:
https://myserver/reports/cover?title=Title&subtitle=Subtitle&info=Informacion

This fails with message
IOError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: UnknownContentError

My understanding is at the moment, the request is passing through nginx, which is expecting the HTTP header with the required client side cert info being passed to the application.  
I encountered a similar issue with Basic HTTP Auth in place, with a 401 Authorisation Error being returned for what I assume are similar reasons.  
Current solutions I have in mind:  
- change method of cover generation that does not require calling back to URL i.e. generate tmp html file on disk instead of URL
- add required forwarded certificate headers within code
- add nginx exception for cover generating URL bypass, not ideal in case of security issue with the htmltopdf

Any guidelines / recommendations for working around this?

**Comment by devGregA** [comment]
@a1ec I believe this PR will fix this issue https://github.com/OWASP/django-DefectDojo/pull/353

**Comment by devGregA** [comment]
#353 merged please feel free to reopen if it isn't fixed for you
