### ISSUE TITLE
User, Superuser, Staff Permissions Question

### ISSUE THREAD

**Issue by StephenNickle** [OWASP/django-DefectDojo#299]
Hello All,

I'm unsure what the different user types are intended to be able to access and how DefectDojo is intended to be setup with multiple users having access to the same products. In my instance of DefectDojo, normal active users and superusers seem to have the same access. They each only have access to view the products on which they are authorized. They are not able to view or create engagements or to create new products. So far, the only way I have been able to change the access available to a user has been to mark the user as Staff, which then seems to give them access to all Products, engagements, users, etc. Is this the way DefectDojo is intended to work?

I originally assumed that I could create a Product as Staff and then have multiple authorized users for that product that could view, add and modify all engagements, tests, findings, etc. for that product only. Is this the way access is intended?

I apologize if this information was already available in the documentation or if I am submitting this question in the wrong place. I appreciate any help you are able to provide. Thank you.

**Comment by devGregA** [comment]
Hi @StephenNickle! Thanks for your question. Staff users are typically engineers / testers. They have access to and can edit all products, engagements, and findings. Authorized users are typically people external to the security team that want to view the details for a specific product. Authorized users can also see the general metrics. Super users can see the metrics on all engineers. If this doesn't answer you question, please feel free to re-open the issue.

**Comment by StephenNickle** [comment]
@devGregA Thank you for your quick response. Having engineers/testers as staff makes sense. My only concern is I would prefer not to give all our staff users access to the Users tab where they can make changes to our other user's accounts. Is there a way to allow a user to have all the staff access for engagements, tests, etc. without giving them access to the users tab? Thanks again for your help!

**Comment by devGregA** [comment]
Hi @StephenNickle, ah gotcha. So the user tab is a little misleading. While staff have access to it and can set the fields, the users do not receive passwords until a super user goes to /admin. That user tab is for adding place holders for contact info. However, if a super user added a password for a user, a staff user could elevate the privileges of a user. I'll add a fix to my backlog, but it could be a couple weeks before I can allocate the time to address it.

**Comment by devGregA** [comment]
Elevating to a bug for tracking.

**Comment by StephenNickle** [comment]
@devGregA That helps clear it up for me. Thank you for your help.

**Comment by devEricA** [comment]
Hi @StephenNickle , I have a fix for this, I am also working on #174. I will submit the fix for this issue with the PR for #174 .

**Comment by himani-dangwal** [comment]
> Hi @StephenNickle, ah gotcha. So the user tab is a little misleading. While staff have access to it and can set the fields, the users do not receive passwords until a super user goes to /admin. That user tab is for adding place holders for contact info. However, if a super user added a password for a user, a staff user could elevate the privileges of a user. I'll add a fix to my backlog, but it could be a couple weeks before I can allocate the time to address it.



> Hi @StephenNickle! Thanks for your question. Staff users are typically engineers / testers. They have access to and can edit all products, engagements, and findings. Authorized users are typically people external to the security team that want to view the details for a specific product. Authorized users can also see the general metrics. Super users can see the metrics on all engineers. If this doesn't answer you question, please feel free to re-open the issue.

Hi @devGregA  ,I have created a user and have just marked him as active. When he tries to close or change status of a finding he is prompted with enter credentials pop up. May I know why

**Comment by madchap** [comment]
This is a current limitation of the role model being used. 

Please refer to #1048 for up-to-date info, and related links. Thanks.
