### ISSUE TITLE
Question: Metrics for Findings per Product Engagement

### ISSUE THREAD

**Issue by StephenNickle** [OWASP/django-DefectDojo#307]
Hi all,
Is it currently possible to view metrics for the number of findings for each severity broken down for each engagement of a product type? For example, let's say I create a new engagement each quarter to scan application X. During that engagement, I run multiple tests on X and include them in the engagement. I report the findings and close the engagement when it is complete. The findings are then supposed to be fixed.

I would like to be able to view the numbers of findings found during each engagement with the finding's severity included. So, in this example, I would like to be able to see if X had more severe findings in quarter 3 than in quarter 2 of 2017 to be able to track on a high level the trends of findings from engagement to engagement.

DefectDojo has many views to break findings down by time period, but I haven't seen a way to easily view finding counts by engagement. I certainly may have missed this. Is this functionality already in place? If not, what would be the closest metric view to it?

Thanks for your help!

**Comment by devGregA** [comment]
Hi @StephenNickle great question! Yes, there is an icon in the top right for both engagements and products. Please see the screen shot below

<img width="1262" alt="screen shot 2017-06-28 at 1 40 12 pm" src="https://user-images.githubusercontent.com/4741312/27654786-b299f78c-5c08-11e7-9632-e6680fdda122.png">
