### ISSUE TITLE
No module named util (Django 1.11.2)

### ISSUE THREAD

**Issue by no-sec-marko** [OWASP/django-DefectDojo#310]
Hi,

I setup a clean install of the defect dojo using the ./setup.bash (master branch) on the following system:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> DISTRIB_CODENAME=xenial
> DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

> Django 1.11.2

If i want to delete an exisiting test under  _/Home / Active Engagements / 1 / Engagement: This Engagement_ the application returns an ImportError "No module named util" based on the _django.contrib.admin.util_ import in line 117 in /dojo/test/views.py:
`117     from django.contrib.admin.util import NestedObjects`

The error based on the django version (from 1.8 to 1.11.2). The package name was change from _django.contrib.admin.util_ to _django.contrib.admin.utils_. The code below will fix the error in Defect Dojo
```
117     try:
118         from django.contrib.admin.util import NestedObjects
119     except ImportError:
120         from django.contrib.admin.utils import NestedObjects
```

Stack:

> ImportError at /test/3/delete
> 
> No module named util
> 
> Request Method: 	GET
> Request URL: 	http://host.de/test/3/delete
> Django Version: 	1.11.2
> Exception Type: 	ImportError
> Exception Value: 	
> 
> No module named util
> 
> Exception Location: 	/opt/django-DefectDojo/dojo/test/views.py in delete_test, line 118
> Python Executable: 	/usr/bin/python
> Python Version: 	2.7.12
> Python Path: 	
> 
> ['/opt/django-DefectDojo',
>  '/usr/local/lib/python2.7/dist-packages/DefectDojo-1.0.5-py2.7.egg',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/home//.local/lib/python2.7/site-packages',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/opt/django-DefectDojo']

**Comment by devGregA** [comment]
Confirmed, working on this now.
