### ISSUE TITLE
Images not available in debug mode

### ISSUE THREAD

**Issue by no-sec-marko** [OWASP/django-DefectDojo#311]
Hi,

I setup a clean install of the defect dojo using the ./setup.bash (master branch) on the following system:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> DISTRIB_CODENAME=xenial
> DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

> Django 1.11.2

After uploading new images in a test, the files are no longer available (http 404). The error relies on the update to django 1.11.x  which remove the media root in debug mode in the _dojo/urls.py_: #250 

Following code change will make the function available again.
dojo/urls.py
```
3 from django.conf.urls.static import static

104 if settings.DEBUG:
105 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by devGregA** [comment]
Hi @no-sec-marko, since you've already figured out the fix would you like to submit the PR so you'll get credit for it? :)
