### ISSUE TITLE
Stale Settings Issue

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#330]
Hi @patriknordlen, I noticed something strange. When a fresh install is done, regardless of the settings, severities use the s-naming convention despite it being disabled. However, if it is toggled (set and unset) it works as expected. Any idea on why this is happening?

**Comment by patriknordlen** [comment]
Hi @devGregA, this is due to that numerical severity has actually been the default setting if nothing has been defined in system settings :)

I'm issuing a PR now that changes this.
