### ISSUE TITLE
Filter Missing Correct Fields

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#331]
Hi @grendel513, I noticed something weird on the metrics page. The filter bar no longer appears in the dropdown. I investigated and discovered it is because we are passing the queryset with `.qs` https://github.com/OWASP/django-DefectDojo/blob/master/dojo/metrics/views.py#L309

So I added another another reference that passed the object without `.qs`, but the filter is now overly verbose 
<img width="1032" alt="screen shot 2017-07-24 at 8 35 51 am" src="https://user-images.githubusercontent.com/4741312/28525873-4b151978-704b-11e7-9d46-823c91717a41.png">

I'm thinking it is an issue with `clear_link`
https://github.com/OWASP/django-DefectDojo/blob/master/dojo/templates/dojo/metrics.html#L123

Could you walk me through clear_link? I can't find great docs on it.

**Comment by grendel513** [comment]
@devGregA - I will take a look

**Comment by devGregA** [comment]
@grendel513 submitted a partial fix

**Comment by grendel513** [comment]
@devGregA pull request #340 fixes this issue and other minor quirks.  Additionally it fixes simple metrics which returned an error.
