### ISSUE TITLE
setup.bash breaks systems with MariaDB installed

### ISSUE THREAD

**Issue by redNixon** [OWASP/django-DefectDojo#334]
For users that are already running MariaDB on Ubuntu 16.04(installed using the [mariaDB repos](https://downloads.mariadb.org/mariadb/repositories/#mirror=ut-austin&distro=Ubuntu&distro_release=xenial--ubuntu_xenial&version=10.2), setup.bash will leave the system in a broken state due it triggering(and auto accepting) the removal of MariaDB-server and attempting to install mysql-server(which fails).

It's my fault for not inspecting the apt command beforehand and not noticing the -y at the end, but I think the installer either needs to check which packages are needed before attempting to install them or at least prompt the user to agree to the system changes.

Output from the setup.bash command:
user@ubuntu1604:/data/git/django-DefectDojo$ sudo bash setup.bash 
Welcome to DefectDojo! This is a quick script to get you up and running.

NEED SUDO PRIVILEGES FOR NEXT STEPS!

Attempting to install required packages...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libjpeg-dev is already the newest version (8c-2ubuntu8).
python-dev is already the newest version (2.7.11-1).
npm is already the newest version (3.5.2-0ubuntu4).
wkhtmltopdf is already the newest version (0.12.2.4-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
nodejs-legacy is already the newest version (4.2.6-dfsg-1ubuntu4.1).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
The following packages were automatically installed and are no longer required:
  galera-3 libdbd-mysql-perl libdbi-perl libgles1-mesa libmircommon5 libterm-readkey-perl linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-70
  linux-headers-4.4.0-70-generic linux-headers-4.4.0-71 linux-headers-4.4.0-71-generic linux-headers-4.4.0-72 linux-headers-4.4.0-72-generic linux-headers-4.4.0-75 linux-headers-4.4.0-75-generic linux-headers-4.4.0-77
  linux-headers-4.4.0-77-generic linux-headers-4.4.0-78 linux-headers-4.4.0-78-generic linux-headers-4.4.0-79 linux-headers-4.4.0-79-generic linux-headers-4.4.0-81 linux-headers-4.4.0-81-generic
  linux-image-4.4.0-62-generic linux-image-4.4.0-66-generic linux-image-4.4.0-70-generic linux-image-4.4.0-71-generic linux-image-4.4.0-72-generic linux-image-4.4.0-75-generic linux-image-4.4.0-77-generic
  linux-image-4.4.0-78-generic linux-image-4.4.0-79-generic linux-image-4.4.0-81-generic linux-image-extra-4.4.0-62-generic linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-70-generic
  linux-image-extra-4.4.0-71-generic linux-image-extra-4.4.0-72-generic linux-image-extra-4.4.0-75-generic linux-image-extra-4.4.0-77-generic linux-image-extra-4.4.0-78-generic linux-image-extra-4.4.0-79-generic
  linux-image-extra-4.4.0-81-generic python-egenix-mxdatetime python-egenix-mxtools snap-confine
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  mysql-client-5.7 mysql-server-5.7 mysql-server-core-5.7
Suggested packages:
  mailx tinyca
The following packages will be REMOVED:
  **mariadb-client-10.2 mariadb-server mariadb-server-10.2 mariadb-server-core-10.2**
The following NEW packages will be installed:
  **libmysqlclient-dev mysql-client-5.7 mysql-server mysql-server-5.7 mysql-server-core-5.7**
0 upgraded, 5 newly installed, 4 to remove and 17 not upgraded.
Need to get 0 B/12.9 MB of archives.
After this operation, 8,833 kB of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 623575 files and directories currently installed.)
**Removing mariadb-server (10.2.7+maria-xenial) ...
Removing mariadb-server-10.2 (10.2.7+maria-xenial) ...
Removing mariadb-client-10.2 (10.2.7+maria-xenial) ...
Removing mariadb-server-core-10.2 (10.2.7+maria-xenial) ...**
Processing triggers for man-db (2.7.5-1) ...
Selecting previously unselected package mysql-client-5.7.
(Reading database ... 623353 files and directories currently installed.)
Preparing to unpack .../mysql-client-5.7_5.7.19-0ubuntu0.16.04.1_amd64.deb ...
Unpacking mysql-client-5.7 (5.7.19-0ubuntu0.16.04.1) ...
Selecting previously unselected package mysql-server-core-5.7.
Preparing to unpack .../mysql-server-core-5.7_5.7.19-0ubuntu0.16.04.1_amd64.deb ...
Unpacking mysql-server-core-5.7 (5.7.19-0ubuntu0.16.04.1) ...
Preparing to unpack .../mysql-server-5.7_5.7.19-0ubuntu0.16.04.1_amd64.deb ...
**Aborting downgrade from (at least) 10.2 to 5.7.**
If are sure you want to downgrade to 5.7, remove the file
/var/lib/mysql/debian-*.flag and try installing again.
dpkg: error processing archive /var/cache/apt/archives/mysql-server-5.7_5.7.19-0ubuntu0.16.04.1_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Selecting previously unselected package libmysqlclient-dev.
Preparing to unpack .../libmysqlclient-dev_5.7.19-0ubuntu0.16.04.1_amd64.deb ...
Unpacking libmysqlclient-dev (5.7.19-0ubuntu0.16.04.1) ...
Selecting previously unselected package mysql-server.
Preparing to unpack .../mysql-server_5.7.19-0ubuntu0.16.04.1_all.deb ...
Unpacking mysql-server (5.7.19-0ubuntu0.16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/mysql-server-5.7_5.7.19-0ubuntu0.16.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by devGregA** [comment]
Hi @redNixon! Thanks for brining this to our attention. This is definitely something we hadn't thought of previously. My plan is to remove the `y`'s so users will at least get the same level of warning they would get out of their OS. If you think there is a better option please let me know!

**Comment by devGregA** [comment]
PR merged
