### ISSUE TITLE
Report Generation not working on Ubuntu Server 16.04 / Support

### ISSUE THREAD

**Issue by mschwarzl** [OWASP/django-DefectDojo#339]
Hi, 

I am using an Ubuntu server 16.04 and not able to generate a custom report.

When I start the task the state keeps on running and does not create a valid PDF.

I used the recommended wkhtlmtopdf.

Is there a possibility to fix this issue?

Cheers,
Martin

**Comment by patriknordlen** [comment]
Did you run the celery worker? It needs to be running in order for any
reports to be generated.

**Comment by mschwarzl** [comment]
Dojo is started using run_dojo.bash - so I think celery is running.

**Comment by mschwarzl** [comment]
Had a permission problem for the user that started run_dojo.bash
