### ISSUE TITLE
Error While Uploading Scan Results

### ISSUE THREAD

**Issue by asdf344** [OWASP/django-DefectDojo#342]
While uploading nessus scan results, HTTP 500 error code is given. Here is the details:

Request Method: | POST
-- | --
http://192.168.33.162:8000/test/14/re_import_scan_results
1.11.4
DoesNotExist
System_Settings matching query does not exist.
/usr/lib/python2.7/site-packages/django/db/models/query.py in get, line 380
/usr/bin/python
2.7.5
['/root/Desktop/django-DefectDojo',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib64/python2.7/site-packages/gtk-2.0',  '/usr/lib/python2.7/site-packages',  '/root/Desktop/django-DefectDojo']
Wed, 9 Aug 2017 03:37:47 -0500

To reproduce the error, upload any .nessus file.

**Comment by devGregA** [comment]
Hi @asdf344 I've fixed this issue with my last PR. Please feel free to reopen if it is not fixed after performing a `git pull`
