### ISSUE TITLE
Question: Are there any plans for the "Additional Information/Metadata"-Fields in the Products?

### ISSUE THREAD

**Issue by S-Schettler** [OWASP/django-DefectDojo#346]
I'm just playing around with DefectDojo v. 1.1.4 and have realized, that the fields of the Product overview don't fit my needs. 
So I have added some fields at Additional Information like "Customer Number" and some other.  When I create a new Product, I have to add all these fields manually, so I just looked at the database and found the table: "custom_field_customfield". 
In this table there are rows named: default_value, field_choices and is_required. 
Have those fields been planned for some additional functionality for the future? ...maybe to "store" the fields for all new products with default values?... This would be really nice to have.
Yet it doesn't seem to make any difference, when I change them over the mysql terminal.

**Comment by devGregA** [comment]
Hi @S-Schettler there is currently a 'metadata' field attached to product that I **think** would work for your use case. If not, you could fork the repo, change the models.py file to meet your needs and then just pull changes from the master repo into your fork.  Hope this helps! Let me know if you have any other questions.
