### ISSUE TITLE
Cannot import Qualys xml reports.

### ISSUE THREAD

**Issue by NShani** [OWASP/django-DefectDojo#358]
Hi,

I setup the defect dojo using the ./setup.bash (master branch) on Ubuntu 16.04. 

When I am trying to import a Qualys XML report, it is not parsing the XML report. It shows the alert saying "Qualys Scan processed, a total of 0 findings were processed ".

**Comment by s-rohil** [comment]
I am getting the same issue. Any support on the above issue?

**Comment by devGregA** [comment]
Hi @NShani and @s-rohil, right now we're just short on resources. @NShani greatly appreciate you sending over a sample scan for debugging. That significantly increases the priority in the queue. However there isn't an ETA yet.

**Comment by NShani** [comment]
Hi @devGregA ,

As I understand this is because Qualys have two types of scans, IP scanning and web application scanning. I was trying to parse a web application scan report. The existing parser is for IP scanning. Thus web application scan report would not parse through the existing parser. I wrote a parser for Qualys web application. It has sent with the this [PR #361 ](https://github.com/OWASP/django-DefectDojo/pull/361) . It would be great if you could review it.

**Comment by devGregA** [comment]
Believe to be fixed via https://github.com/OWASP/django-DefectDojo/pull/397 There is now a new Qualys Webapp Scan should be the option you want to use. Please feel free to reopen if you still have issues

**Comment by alekbc** [comment]
Hi @devGregA , I'm having this issue at version 1.3.0. I tried with both types of scanning (ip scan and web) and I'm getting 0 findings with both.
Thanks,
Alejandro

**Comment by Clarke-AU** [comment]
@alekbc did you try the default Qualys detailed report?  Choosing to download the scan results from a Qualy scan in XML, generates a different XML format.  The DD import parser requires the XML element <ASSET_DATA_REPORT> which is generated when choosing a report output in XML.

**Comment by alekbc** [comment]
Hi @Clarke-AU. According to Qualys tech support, <ASSET_DATA_REPORT> element is only generated using  Qualys API (not by using web-ui). 
I'll try it and let you know.

Regards,
Alejandro
