### ISSUE TITLE
Error Import Scan Results with API

### ISSUE THREAD

**Issue by NShani** [OWASP/django-DefectDojo#360]
Hi,

I have set up the defect dojo using the ./setup.bash (master branch) on Ubuntu 16.04.

I tried to import a scan report using the API. But it shows the following error.

`Response Body

{
  "error_message": "global name 'Resolver404' is not defined",
  "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 221, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 461, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 493, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1401, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/home/xxx/yyy/VulManSys/django-DefectDojo/dojo/api.py\", line 884, in obj_create\n    self.is_valid(bundle)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1313, in is_valid\n    errors = self._meta.validation.is_valid(bundle, bundle.request)\n\n  File \"/home/nadeeshani/Desktop/ExternalProducts/VulManSys/Temp/django-DefectDojo/dojo/api.py\", line 805, in is_valid\n    get_pk_from_uri(uri=bundle.data['engagement'])\n\n  File \"/home/nadeeshani/Desktop/ExternalProducts/VulManSys/Temp/django-DefectDojo/dojo/api.py\", line 748, in get_pk_from_uri\n    except Resolver404:\n\nNameError: global name 'Resolver404' is not defined\n"
}`

**Comment by devGregA** [comment]
@NShani Thank you for your awesome work to get this fixed! Aaron addressed a couple other discovered issues and incorporated your code into his PR. If you would like a DefectDojo shirt as a thank you for your contribution, please email me greg.anderson@owasp.org
