### ISSUE TITLE
Problem during Installation

### ISSUE THREAD

**Issue by Horst88** [OWASP/django-DefectDojo#373]
Hello,

I encouter the following problem trying to install defect dojo on ubuntu 17.04. I use the setup.bash script to install. During the installation the following error occurs, which I have not been able to fix.

_Collecting Django==1.11.2 (from DefectDojo==1.2.0)
  Using cached Django-1.11.2-py2.py3-none-any.whl
Collecting MySQL-python (from DefectDojo==1.2.0)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vor4kxpf/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-build-vor4kxpf/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    **ImportError: No module named 'ConfigParser'**
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vor4kxpf/MySQL-python/_**

Please provide further assistance.

**Comment by Horst88** [comment]
Is the setup.bash script compatible with python 3.* or are there constraints on the python version?

**Comment by devGregA** [comment]
Hi @Horst88. Right now we only support python 2.7. Python 3 is under active development and with a large code base we want to wait until the deprecation waves are over. Even if you want to use python3 as your default option, virtual environments are great / easy option for running 2.7

https://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv
http://docs.python-guide.org/en/latest/dev/virtualenvs/#lower-level-virtualenv

**Comment by devGregA** [comment]
@pagliacci I'm not sure what you're referring to. Was there a change to Python2.7?

**Comment by pagliacci** [comment]
Sorry for that @devGregA . I didn't know where else i can ask this question.

The problem is that Cyrillic chars are not supported in DefectDojo. And it crashes when Cyrillic chars are entered in any field.

This may occur due to the problems with Python 2.7 and cyrillic chars. And this problem will be solved when application started to work with Python 3.

**Comment by devGregA** [comment]
Hi @pagliacci, no need to apologize. Please open a new issue so we can track it properly. I'm working on a slight DB change that may fix the issue with character sets. To be completely honest, I'm not sure when we will begin the migration from 2.7 to 3. When you open the issue, please include any extra information you can to help us reproduce the error. The more info we have, the more able we are to come up with a hot fix as a potential temporary solution.
