### ISSUE TITLE
Login-credentials  for Demo

### ISSUE THREAD

**Issue by Horst88** [OWASP/django-DefectDojo#374]
Hi,

the credentials admin, administrator do not work on https://defectdojo.pythonanywhere.com/login

Regards

**Comment by devGregA** [comment]
Thanks @Horst88 someone must have changed it. I'll fix this shortly

**Comment by devGregA** [comment]
Shold be fixed. Need @grendel513 to show me how to restart the server. (Ran the cleanup scripts etc)

**Comment by devGregA** [comment]
@Horst88 figured it out. It is fixed.

**Comment by matbgn** [comment]
Hi,

Seems that somebody changed it again. Not able to login to demo

Could you please take a look?

**Comment by mtesauro** [comment]
@matbgn 
So, the credentials on the Demo get reset approx every 30 minutes so if this happens to you again, wait a bit and try again.

Additionally, the entire DB is wiped and restored to a fresh copy every 24 hours so worst case, that will also reset the demo login credentials.

**Comment by matbgn** [comment]
Thanks good to know for the future!
