### ISSUE TITLE
Error importing Burp Scan results with API

### ISSUE THREAD

**Issue by s-rohil** [OWASP/django-DefectDojo#380]
When i'm trying to import burp scan results with API, I get the following error:
`{"error": "[u'This field cannot be blank.']"}`

I am using the API Docs in defect dojo to test run all the API calls.
My API call:
`{
  "minimum_severity": "Low",
  "scan_date": "2017-10-15",
  "verified": true,
  "file":"path/to/burp/scan/result.xml",
  "tags": null,
  "active": true,
  "engagement": "/api/v1/engagements/42/",
  "scan_type": "Burp Scan"
}
`

**Comment by s-rohil** [comment]
@devGregA , we have the null set to True in our local code base.

**Comment by devGregA** [comment]
@s-rohil would it be possible to get a sample scan?

**Comment by devGregA** [comment]
Should be fixed. Feel free to reopen if it isn't
