### ISSUE TITLE
Findings severities - No Informational?

### ISSUE THREAD

**Issue by rkane-nm** [OWASP/django-DefectDojo#383]
Hi,
When looking to add findings, there are 4 severities (Low, Med, High, Crit). The documentation shows that there should be Informational, as well. The dashboard even looks like it will support it and there's references to informational in the code itself (in some cases, looks like it's accounted for). But, there's no way to add an informational finding (as far as I can tell)... Is there a way we can add informational findings? I attempted to change the severity in the admin section of an item... but it blew up the dashboard, so no dice there. Any help with this one?
Thanks

**Comment by devGregA** [comment]
Hi @rkane-nm could you screenshot the error that occurred when you added the severity to the admin interface and share it here? I think I can push an easy fix.

**Comment by rkane-nm** [comment]
Turns out that error wasn't a problem. It was because I typed in "Informational" instead of "Info". Once I changed it to "Info" it was fine. But is there a reason Informational isn't in the severity drop downs within the overall application?

**Comment by devGregA** [comment]
Hi @rkane-nm I forget why it was removed originally. We still accept 'info' level severity for scanners, but it isn't exposed as an editable option. I **think** there was UI issues, but I can look into re-adding to the UI since it seems like there is value in having it.

**Comment by devGregA** [comment]
Fixed: https://github.com/OWASP/django-DefectDojo/pull/405
