### ISSUE TITLE
Table of Contents always on Top in PDF Reports

### ISSUE THREAD

**Issue by TommyJ1994** [OWASP/django-DefectDojo#392]
Please use the following template when submitting issues:

## Issue Template
The table of contents always appear on top in PDF's

### Issue Type 
- [ ] Bug

### Operating System 
Fedora 26

### Install

- [ ] setup.bash

### Steps to Reproduce
Create a custom report that has a table of contents. Place the table of contents at the bottom of the report or anywhere but the top. When you generate the report, the table of contents is always on the first page.

**Comment by rkane-nm** [comment]
We figured this one out... you have to go to the pdfkit call and add "cover_first: True" as one of the parameters. Why that's not a pdfkit default, I have no idea.

Dojo/tasks.py: 
pdf = pdfkit.from_string(bytes,
                                 False,
                                 configuration=config,
                                 cover=cover,
                                 toc=toc)  <-- add "**, cover_first: True**" there before the ending parenthesis.

**Comment by TommyJ1994** [comment]
PR opened
