### ISSUE TITLE
Installation problem - bower

### ISSUE THREAD

**Issue by Horst88** [OWASP/django-DefectDojo#395]
Please use the following template when submitting issues:

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
Trying to install in a virtualenv
http://defectdojo.readthedocs.io/en/latest/getting-started.html#install-script
Step 3 Bower

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 17.*

### Install

- [x ] setup.bash
- [ ] docker

### Steps to Reproduce
Problem is at step 3 from the installation description

### Console Logs (optional)
python manage.py bower install
Traceback (most recent call last):
File "manage.py", line 8 in <module>
from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by Horst88** [comment]
So I installed defect dojo without virtualenv and had no problems, ... I did not perform the steps 3 and 4, ... Are they still necessary? 
In the virtualenv installation the ui was broken, .... when I starated defect-dojo.

**Comment by devGregA** [comment]
@Horst88 no, it shouldn't be necessary any longer. For folks doing custom builds, installing the native django way, or other custom methods it would be necessary. For certain code changes (updates) it would also be necessary. Will update the docs when I can. I'll leave this open for tracking. Thank you for brining it to our attention!
