### ISSUE TITLE
Bulk upload of products, endpoints, metadata

### ISSUE THREAD

**Issue by Horst88** [OWASP/django-DefectDojo#396]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [ x] Enhancement

### Description
I would like to be able to do a zap baseline scan on all products that are stored in defectDojo. The idea would be to write a script that iterates over all products gets the endpoints for each product, perform a baseline scan and then upload the result.
I am missing the ability to create endpoints and metadata over the API.

Doing it the other way around, meaning doing a baseline scan and then uploading it to defectDojo would mean to store the URL and the defectDojo product ID outside of defectDojo, .... I would prefer to use defectDojo as the single source of truth, ...

What are your thoughts on this?

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by Horst88** [comment]
An API for the tags of products would also be awesome, then I could automatically enrich the products with more data describing the product.

**Comment by devGregA** [comment]
Hi @Horst88 , this is actively being developed!
https://github.com/OWASP/django-DefectDojo/issues/366 and 
https://github.com/OWASP/django-DefectDojo/issues/365

Closing because I think this is covered by the two issues linked above. If you feel differently, please don't hesitate to reopen.
