### ISSUE TITLE
Add a #goodfirstbug label to issues category on Github so new devs wanted to get engaged can focus on those ones

### ISSUE THREAD

**Issue by nhajiyani** [OWASP/django-DefectDojo#399]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Enhancement

### Description
Add #goodfirstbug label to the category of issues. This would help new people looking to get engaged to focus taking those on. Also it can be a quick triage mechanism and that way more engaged devs can take on the more involved issues and also there would be a shorter run way for folks wanting to get started quickly.

**Comment by devGregA** [comment]
@nhajiyani agree 100%. We used to have some easier issues labeled when we had students engaged via the OWASP Code Sprint and a couple other programs. I'll go through our log again and try to identify some with additional notes to help folks get involved.

**Comment by devGregA** [comment]
Added Beginner Friendly
