### ISSUE TITLE
Installations Improvements, requirements.txt

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#402]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
Update the installation to include a separate requirement.txt file that can be consumed in the installation scripts and the ansible configuration. Also review how environment variables are set and the best way to merge up the installation process so there isn't duplication.

**Comment by devGregA** [comment]
@aaronweaver will include with my dedupe changes
