### ISSUE TITLE
Landing page does not display properly

### ISSUE THREAD

**Issue by fuckgitb** [OWASP/django-DefectDojo#416]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [x] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [x] setup.bash
- [ ] docker

### Console Logs (optional)

after the server run ,i found this issus
![defect404](https://user-images.githubusercontent.com/7565173/33643623-3539651a-da7b-11e7-8576-b2096734c2c3.png)
![defectdojo](https://user-images.githubusercontent.com/7565173/33643627-3c6422d0-da7b-11e7-93eb-9f1f58c0611c.png)

how to fix it

**Comment by aaronweaver** [comment]
You need to collect the static files:

cd defect-dojo
cd components
bower install
cd ..

./manage.py collectstatic --noinput

**Comment by devGregA** [comment]
This might be a permissions issue related to OSX 
`
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

`
Fixed it for me.

If you still have issues with the install script. After running setup.bash cd into components and run:

` bower install `

return to /django-Defectdojo/ and run:

` python manage.py collectstatic --noinput`
