### ISSUE TITLE
Missing JIRA project config option/field?

### ISSUE THREAD

**Issue by xthk** [OWASP/django-DefectDojo#423]
### Issue Type 
- [X] Bug
- [X] Enhancement

### Description

I have problems setting up the JIRA integration. In the UI dialog there is no JIRA project to configured. As far as I know this is a mandatory field for JIRA (and the JIRA API).

Screenshot:

<img width="560" alt="new_jira_configuration_2017-12-11" src="https://user-images.githubusercontent.com/5803044/33824655-6ab7d75c-de5f-11e7-970a-69d319d00b70.png">

### Operating System 

Ubuntu 16.04, Python 2.7.11, Django 1.11.2.

### Install

- [ ] setup.bash
- [ ] docker
- [X] custom

### Steps to Reproduce

- Go to /jira/add
- Search for "JIRA project"

**Comment by devGregA** [comment]
Hi @xthk JIRA Projects are tied to DefectDojo "Products" when you create/edit a new product once JIRA is enabled there will be a new field.
