### ISSUE TITLE
bower deprecation warning

### ISSUE THREAD

**Issue by xthk** [OWASP/django-DefectDojo#426]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description

```
sudo npm install -g bower
```
(https://github.com/OWASP/django-DefectDojo/blob/master/setup.bash#L173)

leads to a bower deprecation warning:

> npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

### Steps to Reproduce

Just run 

```
sudo npm install -g bower
```

from the project's root directory.

**Comment by aaronweaver** [comment]
@xthk this was addressed in yesterday's PR. Swapped out bower with YARN.
