### ISSUE TITLE
Add/Edit New Issue Type for JIRA Config

### ISSUE THREAD

**Issue by ishangirdhar** [OWASP/django-DefectDojo#436]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description:
We have created a custom JIRA Issue Type in our enterprise JIRA, which allows us to capture additional details of the security issues we raise. This issuetype also have a custom workflow, which allows us to track the progress. Name of our custom issuetype is "Security Bug" that we have configured in our jira.

However, in DefectDojo's configuration I see pre-defined issuestypes only like (Bug, Tasks, Story, Spike). Is there any way I can add/edit/update in code or in DB to be able to add custom issuetype? 

### Steps to Reproduce
Configuration -> JIRA

**Comment by devGregA** [comment]
@ishangirdhar should be an easy change. Give me a couple days to investigate.

**Comment by ishangirdhar** [comment]
Thanks @devGregA

**Comment by ishangirdhar** [comment]
Hi @devGregA,

I have good understanding of JIRA Bi-directional integration, however not so much in Django, Any guidance regarding would be appreciated, I can change the code and do some testing.

-Ishan

**Comment by devGregA** [comment]
@ishangirdhar I've looked into this, and I think a one-off solution might be easier than changing the actual code. Reason for this is that we start with all the default issue types, so security folks do not have to be familiar with JIRA configurations. To add a 'Security Bug choice', and make it the default option, make the following change:
https://github.com/OWASP/django-DefectDojo/blob/master/dojo/models.py#L1031
`
                            choices=(
                                ('Security Bug', 'Security Bug'
                                ('Task', 'Task'),
                                ('Story', 'Story'),
                                ('Epic', 'Epic'),
                                ('Spike', 'Spike'),
                                ('Bug', 'Bug')),
                            default='Security Bug')
`
