### ISSUE TITLE
Slack Notifications aren't working

### ISSUE THREAD

**Issue by ishangirdhar** [OWASP/django-DefectDojo#437]
### Issue Type 
- [x] Bug
- [ ] Enhancement

## Hi Folks,

I have enabled slack integration by adding slack token and channel name yet I am not receiving any slack notifications. I have celery and celery beat service running in the background. I have enabled all the events on personal and global scope. I have triggered the events multiple times by adding adding engagements, tests etc. However, I do see success message api.slack.com but I don't receive any notification message on slack, neither in the channel nor on personal chat.

### Operating System 
Ubuntu 16.04

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce
1. Configuration -> System Settings -> Check Enable Slack Notification
2. Create token from, for a bot from https://api.slack.com/tokens
3. Add Slack API Token and Channel Name and Slack username
4. Configuration -> Notifications -> Enable all events in Global and Personal Scope

### Screenshots (optional)
<img width="1175" alt="screen shot 2017-12-29 at 8 59 38 pm" src="https://user-images.githubusercontent.com/2884252/34437693-6f7696b8-ecdb-11e7-81cf-9ccf2c80a0ce.png"> 

Note: Slack token is of course has been regenerated after taking screenshot.

### Console Logs (optional)
```
Starting new HTTPS connection (1): slack.com
https://slack.com:443 "POST /api/chat.postMessage HTTP/1.1" 200 55
Starting new HTTPS connection (1): slack.com
https://slack.com:443 "POST /api/chat.postMessage HTTP/1.1" 200 55
Starting new HTTPS connection (1): slack.com
https://slack.com:443 "POST /api/chat.postMessage HTTP/1.1" 200 55
[pid: 26004|app: 0|req: 4/50] 10.53.0.244 () {60 vars in 1322 bytes} [Fri Dec 29 20:56:51 2017] POST /product/1/new_engagement => generated 0 bytes in 1233 msecs (HTTP/1.1 302) 7 headers in 377 bytes (1 switches on core 0)
[pid: 26003|app: 0|req: 2/51] 10.53.0.244 () {54 vars in 1305 bytes} [Fri Dec 29 20:56:52 2017] GET /engagement/7/add_tests => generated 26191 bytes in 208 msecs (HTTP/1.1 200) 8 headers in 495 bytes (1 switches on core 0)
```

**Comment by ishangirdhar** [comment]
Please ignore this, I realised I was adding a token created for an app, instead for a bot user.

**Comment by rafaelnepo92** [comment]
Hello [ishangirdhar](https://github.com/ishangirdhar) I managed to integrate with the bot key, but it does not reach the channel I would like, only a notification arrives in Slackbot, would you know how to help me?

**Comment by mikesindieiev** [comment]
@rafaelnepo92 still relevant to me. Private messages work fine but the messages do not reach a public channel
