### ISSUE TITLE
deduplication - documentation for starting celery

### ISSUE THREAD

**Issue by Horst88** [OWASP/django-DefectDojo#440]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [x ] Enhancement

### Description
Please update the documentation in order for the deduplication to work. Please add advice for using celebry.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by devGregA** [comment]
@Horst88 

I've updated the Getting Started guide to use run_dojo.bash (http://defectdojo.readthedocs.io/en/latest/getting-started.html), and I've updated the dedupe documentation (https://defectdojo.readthedocs.io/en/latest/features.html#issue-consolidation).
