### ISSUE TITLE
Review and Approve Findings

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#64]
Sometimes findings need to be peer reviewed by other reviewers. I'd like the ability to be able to assign a status to the finding of 'Under Review'. When a finding is under review that finding can be assigned to other system reviewers and will notify them that the finding needs to be reviewed. Optionally an email should be sent out notifying a reviewer that there is a finding that should be reviewed.

**Comment by devGregA** [comment]
Hmm. Status is an interesting field because it is generated on the fly based on other selections in the finding model: https://github.com/rackerlabs/django-DefectDojo/blob/master/dojo/models.py#l527.
It's probably not the best model, but that's how it evolved over time. I think the easiest way to incorporate this would be to add a boolean field to finding as under_review. Then in status add a check. What about how this would relate to the verified field? This might be a good candidate for a plugin vs core like @grendel513 did with surveys https://github.com/grendel513/defectDojo-engagement-survey

**Comment by grendel513** [comment]
@aaronweaver in looking at #62, it would have to be completed before we can move on this one.  Do we think those folks would ever be assigned a Finding for review?  Are we strictly sticking to Staff and Superusers as reviewers?

**Comment by grendel513** [comment]
@aaronweaver, @devGregA - should Findings under review be counted in the metrics?  If yes, then no code changes are needed.  If no, then I will have to dig through all the places where metrics are calculated and add the additional check.

**Comment by devGregA** [comment]
I think that findings under review are equivalent to not verified findings and could use the same boolean?

**Comment by grendel513** [comment]
@aaronweaver, @devGregA - perfect, that is the way i started coding it.  As soon as it is mark for review the Active attribute will be set to false.  Everything that acts on the active switch should fall in line.  Thanks!

**Comment by grendel513** [comment]
@aaronweaver, @devGregA - Findings are now able to be marked for review.  Users are able to select any
staff member to review the finding for accuracy.  When a finding is marked
for review it is marked inactive and unverified.  When reviewer clears
review, they have the option to set the findings status and must also leave
a new note to document verification.

This update requires the following commands:
./manage makemigrations dojo
./manage migrate
./manage collectstatic

<img width="1332" alt="screen shot 2016-11-06 at 2 42 29 pm" src="https://cloud.githubusercontent.com/assets/233694/20041609/eb326f3c-a431-11e6-8aea-2584b41356d3.png">
<img width="1057" alt="screen shot 2016-11-06 at 2 43 28 pm" src="https://cloud.githubusercontent.com/assets/233694/20041613/eb35842e-a431-11e6-9995-8ebe27ebb06e.png">
<img width="1034" alt="screen shot 2016-11-06 at 2 43 40 pm" src="https://cloud.githubusercontent.com/assets/233694/20041611/eb346382-a431-11e6-8e3e-d339ed58ebdd.png">
<img width="1016" alt="screen shot 2016-11-06 at 2 44 07 pm" src="https://cloud.githubusercontent.com/assets/233694/20041612/eb35a7a6-a431-11e6-8891-20eeffd43646.png">
<img width="1318" alt="screen shot 2016-11-06 at 2 44 18 pm" src="https://cloud.githubusercontent.com/assets/233694/20041614/eb37f39e-a431-11e6-8947-7bee5b15bdfe.png">
<img width="1321" alt="screen shot 2016-11-06 at 2 45 51 pm" src="https://cloud.githubusercontent.com/assets/233694/20041610/eb3466ca-a431-11e6-8b4d-06f151bb03c7.png">
<img width="1018" alt="screen shot 2016-11-06 at 2 49 35 pm" src="https://cloud.githubusercontent.com/assets/233694/20041615/eb4305ae-a431-11e6-9e1a-1832885f0a0a.png">
<img width="1320" alt="screen shot 2016-11-06 at 2 50 13 pm" src="https://cloud.githubusercontent.com/assets/233694/20041616/eb44fff8-a431-11e6-9640-ac10c985e9eb.png">
