### ISSUE TITLE
Credential Manager (Environment)

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#97]
### Make sure you assign this issue to yourself so contributors do not duplicate effort.

Authenticated scanning requires setting up credentials and roles to the appropriate environment. Often times these credentials need to be shared by the pentesting team. 

Develop a Credential Manager in Dojo that replaces or modifies the `Development_Environment` tied to the `Test` model with the following fields:
- username
- password  
- environment (dev, staging, prod)
- URL

Credentials would be on the product level and with the ability to assign them to a particular test. For example, often times testing will be done with several roles. During finding upload the tester would have the ability to specify which credentials for that product were used. This would facilitate faster re-testing as the credentials used should then be linked from the finding page.

Due to the sensitive nature of this feature, proper encryption and logging is required.

**Comment by davevs** [comment]
Good idea. Maybe using Hashicorp Vault for this might be a sensible idea?

**Comment by devGregA** [comment]
@aaronweaver  please see my modified description above and make revisions as necessary so we can launch as a swag issue.

**Comment by aaronweaver** [comment]
Pending PR: https://github.com/OWASP/django-DefectDojo/pull/243
