### ISSUE TITLE
Integration with Faraday IPE

### ISSUE THREAD

**Issue by davevs** [OWASP/django-DefectDojo#99]
With respect to the importing of issues, I think a lot of time can be saved by making a connection with Faraday IPE. (Faraday is a collaboration pentesting environment that currently can handle 40+ security tools). Using F-IPE for aggregation and assessing the issues and importing them into ddojo prevents having to develop imports for all tools. 

(btw: I had a quick chat with the faraday maintainer on twitter and he's interested)

**Comment by aaronweaver** [comment]
@devevs Can you share the file format and a sample file?

**Comment by davevs** [comment]
From the Faraday wiki (https://github.com/infobyte/faraday/wiki/Exporting-the-information):
Actually Faraday supports CSV Exporting from it's UI, just right click in the workspace and export to a csv file. The current output format is in the form:

found date | severity level | service parent | target | name | vulnerability description | data field | references

I'll try to create an actual example later today.

**Comment by davevs** [comment]
Here's a real sample:

`"date","name","severity","service","target","desc","data","refs"
"8/27/2016","Allowed HTTP Methods: GET, HEAD ","info","(5984/tcp) http","127.0.0.1","","",""
"8/27/2016","This might be interesting...","info","(5984/tcp) http","127.0.0.1","","","OSVDB-ID: 3092"
"8/27/2016","MyWebServer 1.0.2 is vulnerable to HTML injection. Upgrade to a later version.","info","(5984/tcp) http","127.0.0.1","","","OSVDB-ID: 6659"
`

**Comment by devGregA** [comment]
@davevs Please see our call for scans https://www.linkedin.com/pulse/call-scans-news-project-updates-owasp-defectdojo-greg-anderson/
